//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.MesWebSvr {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Thok.WMS.Interface/", ConfigurationName="MesWebSvr.AHZY_ESB_WMS_TRANSSVSoap")]
    public interface AHZY_ESB_WMS_TRANSSVSoap {
        
        // CODEGEN: Generating message contract since element name bominfoXML from namespace http://Thok.WMS.Interface/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Thok.WMS.Interface/PFK_YZPF_PFXD", ReplyAction="*")]
        Test.MesWebSvr.PFK_YZPF_PFXDResponse PFK_YZPF_PFXD(Test.MesWebSvr.PFK_YZPF_PFXDRequest request);
        
        // CODEGEN: Generating message contract since element name abolishinfoXML from namespace http://Thok.WMS.Interface/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Thok.WMS.Interface/PFK_YZPF_PFFZ", ReplyAction="*")]
        Test.MesWebSvr.PFK_YZPF_PFFZResponse PFK_YZPF_PFFZ(Test.MesWebSvr.PFK_YZPF_PFFZRequest request);
        
        // CODEGEN: Generating message contract since element name prepareplanXML from namespace http://Thok.WMS.Interface/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Thok.WMS.Interface/PFK_YLBLTL_XFZSBLJH", ReplyAction="*")]
        Test.MesWebSvr.PFK_YLBLTL_XFZSBLJHResponse PFK_YLBLTL_XFZSBLJH(Test.MesWebSvr.PFK_YLBLTL_XFZSBLJHRequest request);
        
        // CODEGEN: Generating message contract since element name movestockXML from namespace http://Thok.WMS.Interface/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Thok.WMS.Interface/PFK_YLBLTL_XFYLCKD", ReplyAction="*")]
        Test.MesWebSvr.PFK_YLBLTL_XFYLCKDResponse PFK_YLBLTL_XFYLCKD(Test.MesWebSvr.PFK_YLBLTL_XFYLCKDRequest request);
        
        // CODEGEN: Generating message contract since element name backstockXML from namespace http://Thok.WMS.Interface/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Thok.WMS.Interface/PFK_YLBLTL_XFTLD", ReplyAction="*")]
        Test.MesWebSvr.PFK_YLBLTL_XFTLDResponse PFK_YLBLTL_XFTLD(Test.MesWebSvr.PFK_YLBLTL_XFTLDRequest request);
        
        // CODEGEN: Generating message contract since element name materialfeedXML from namespace http://Thok.WMS.Interface/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Thok.WMS.Interface/PFK_YLBL_BLCK", ReplyAction="*")]
        Test.MesWebSvr.PFK_YLBL_BLCKResponse PFK_YLBL_BLCK(Test.MesWebSvr.PFK_YLBL_BLCKRequest request);
        
        // CODEGEN: Generating message contract since element name estimateparamsXML from namespace http://Thok.WMS.Interface/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Thok.WMS.Interface/PFK_YLCS", ReplyAction="*")]
        Test.MesWebSvr.PFK_YLCSResponse PFK_YLCS(Test.MesWebSvr.PFK_YLCSRequest request);
        
        // CODEGEN: Generating message contract since element name productionplanXML from namespace http://Thok.WMS.Interface/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Thok.WMS.Interface/PFK_YLTC_ZSJH", ReplyAction="*")]
        Test.MesWebSvr.PFK_YLTC_ZSJHResponse PFK_YLTC_ZSJH(Test.MesWebSvr.PFK_YLTC_ZSJHRequest request);
        
        // CODEGEN: Generating message contract since element name stockoutXML from namespace http://Thok.WMS.Interface/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Thok.WMS.Interface/PFK_YLTC_GDXF", ReplyAction="*")]
        Test.MesWebSvr.PFK_YLTC_GDXFResponse PFK_YLTC_GDXF(Test.MesWebSvr.PFK_YLTC_GDXFRequest request);
        
        // CODEGEN: Generating message contract since element name stockoutcanceXML from namespace http://Thok.WMS.Interface/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Thok.WMS.Interface/PFK_YLTC_GDQX", ReplyAction="*")]
        Test.MesWebSvr.PFK_YLTC_GDQXResponse PFK_YLTC_GDQX(Test.MesWebSvr.PFK_YLTC_GDQXRequest request);
        
        // CODEGEN: Generating message contract since element name searchparamsXML from namespace http://Thok.WMS.Interface/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Thok.WMS.Interface/PFK_KCGX_KCCX", ReplyAction="*")]
        Test.MesWebSvr.PFK_KCGX_KCCXResponse PFK_KCGX_KCCX(Test.MesWebSvr.PFK_KCGX_KCCXRequest request);
        
        // CODEGEN: Generating message contract since element name storesourceXML from namespace http://Thok.WMS.Interface/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Thok.WMS.Interface/PFK_KCGX_KGXX", ReplyAction="*")]
        Test.MesWebSvr.PFK_KCGX_KGXXResponse PFK_KCGX_KGXX(Test.MesWebSvr.PFK_KCGX_KGXXRequest request);
        
        // CODEGEN: Generating message contract since element name leaforiginalXML from namespace http://Thok.WMS.Interface/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Thok.WMS.Interface/PFK_JCSJ_YYCD", ReplyAction="*")]
        Test.MesWebSvr.PFK_JCSJ_YYCDResponse PFK_JCSJ_YYCD(Test.MesWebSvr.PFK_JCSJ_YYCDRequest request);
        
        // CODEGEN: Generating message contract since element name leafstyleXML from namespace http://Thok.WMS.Interface/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Thok.WMS.Interface/PFK_JCSJ_YYXT", ReplyAction="*")]
        Test.MesWebSvr.PFK_JCSJ_YYXTResponse PFK_JCSJ_YYXT(Test.MesWebSvr.PFK_JCSJ_YYXTRequest request);
        
        // CODEGEN: Generating message contract since element name leafcategoryXML from namespace http://Thok.WMS.Interface/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Thok.WMS.Interface/PFK_JCSJ_YYLX", ReplyAction="*")]
        Test.MesWebSvr.PFK_JCSJ_YYLXResponse PFK_JCSJ_YYLX(Test.MesWebSvr.PFK_JCSJ_YYLXRequest request);
        
        // CODEGEN: Generating message contract since element name leafgradeXML from namespace http://Thok.WMS.Interface/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Thok.WMS.Interface/PFK_JCSJ_YYDJ", ReplyAction="*")]
        Test.MesWebSvr.PFK_JCSJ_YYDJResponse PFK_JCSJ_YYDJ(Test.MesWebSvr.PFK_JCSJ_YYDJRequest request);
        
        // CODEGEN: Generating message contract since element name leafXML from namespace http://Thok.WMS.Interface/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Thok.WMS.Interface/PFK_JCSJ_YY", ReplyAction="*")]
        Test.MesWebSvr.PFK_JCSJ_YYResponse PFK_JCSJ_YY(Test.MesWebSvr.PFK_JCSJ_YYRequest request);
        
        // CODEGEN: Generating message contract since element name tobXML from namespace http://Thok.WMS.Interface/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Thok.WMS.Interface/PFK_JCSJ_YS", ReplyAction="*")]
        Test.MesWebSvr.PFK_JCSJ_YSResponse PFK_JCSJ_YS(Test.MesWebSvr.PFK_JCSJ_YSRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PFK_YZPF_PFXDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PFK_YZPF_PFXD", Namespace="http://Thok.WMS.Interface/", Order=0)]
        public Test.MesWebSvr.PFK_YZPF_PFXDRequestBody Body;
        
        public PFK_YZPF_PFXDRequest() {
        }
        
        public PFK_YZPF_PFXDRequest(Test.MesWebSvr.PFK_YZPF_PFXDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Thok.WMS.Interface/")]
    public partial class PFK_YZPF_PFXDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string bominfoXML;
        
        public PFK_YZPF_PFXDRequestBody() {
        }
        
        public PFK_YZPF_PFXDRequestBody(string bominfoXML) {
            this.bominfoXML = bominfoXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PFK_YZPF_PFXDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PFK_YZPF_PFXDResponse", Namespace="http://Thok.WMS.Interface/", Order=0)]
        public Test.MesWebSvr.PFK_YZPF_PFXDResponseBody Body;
        
        public PFK_YZPF_PFXDResponse() {
        }
        
        public PFK_YZPF_PFXDResponse(Test.MesWebSvr.PFK_YZPF_PFXDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Thok.WMS.Interface/")]
    public partial class PFK_YZPF_PFXDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PFK_YZPF_PFXDResult;
        
        public PFK_YZPF_PFXDResponseBody() {
        }
        
        public PFK_YZPF_PFXDResponseBody(string PFK_YZPF_PFXDResult) {
            this.PFK_YZPF_PFXDResult = PFK_YZPF_PFXDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PFK_YZPF_PFFZRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PFK_YZPF_PFFZ", Namespace="http://Thok.WMS.Interface/", Order=0)]
        public Test.MesWebSvr.PFK_YZPF_PFFZRequestBody Body;
        
        public PFK_YZPF_PFFZRequest() {
        }
        
        public PFK_YZPF_PFFZRequest(Test.MesWebSvr.PFK_YZPF_PFFZRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Thok.WMS.Interface/")]
    public partial class PFK_YZPF_PFFZRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string abolishinfoXML;
        
        public PFK_YZPF_PFFZRequestBody() {
        }
        
        public PFK_YZPF_PFFZRequestBody(string abolishinfoXML) {
            this.abolishinfoXML = abolishinfoXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PFK_YZPF_PFFZResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PFK_YZPF_PFFZResponse", Namespace="http://Thok.WMS.Interface/", Order=0)]
        public Test.MesWebSvr.PFK_YZPF_PFFZResponseBody Body;
        
        public PFK_YZPF_PFFZResponse() {
        }
        
        public PFK_YZPF_PFFZResponse(Test.MesWebSvr.PFK_YZPF_PFFZResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Thok.WMS.Interface/")]
    public partial class PFK_YZPF_PFFZResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PFK_YZPF_PFFZResult;
        
        public PFK_YZPF_PFFZResponseBody() {
        }
        
        public PFK_YZPF_PFFZResponseBody(string PFK_YZPF_PFFZResult) {
            this.PFK_YZPF_PFFZResult = PFK_YZPF_PFFZResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PFK_YLBLTL_XFZSBLJHRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PFK_YLBLTL_XFZSBLJH", Namespace="http://Thok.WMS.Interface/", Order=0)]
        public Test.MesWebSvr.PFK_YLBLTL_XFZSBLJHRequestBody Body;
        
        public PFK_YLBLTL_XFZSBLJHRequest() {
        }
        
        public PFK_YLBLTL_XFZSBLJHRequest(Test.MesWebSvr.PFK_YLBLTL_XFZSBLJHRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Thok.WMS.Interface/")]
    public partial class PFK_YLBLTL_XFZSBLJHRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string prepareplanXML;
        
        public PFK_YLBLTL_XFZSBLJHRequestBody() {
        }
        
        public PFK_YLBLTL_XFZSBLJHRequestBody(string prepareplanXML) {
            this.prepareplanXML = prepareplanXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PFK_YLBLTL_XFZSBLJHResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PFK_YLBLTL_XFZSBLJHResponse", Namespace="http://Thok.WMS.Interface/", Order=0)]
        public Test.MesWebSvr.PFK_YLBLTL_XFZSBLJHResponseBody Body;
        
        public PFK_YLBLTL_XFZSBLJHResponse() {
        }
        
        public PFK_YLBLTL_XFZSBLJHResponse(Test.MesWebSvr.PFK_YLBLTL_XFZSBLJHResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Thok.WMS.Interface/")]
    public partial class PFK_YLBLTL_XFZSBLJHResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PFK_YLBLTL_XFZSBLJHResult;
        
        public PFK_YLBLTL_XFZSBLJHResponseBody() {
        }
        
        public PFK_YLBLTL_XFZSBLJHResponseBody(string PFK_YLBLTL_XFZSBLJHResult) {
            this.PFK_YLBLTL_XFZSBLJHResult = PFK_YLBLTL_XFZSBLJHResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PFK_YLBLTL_XFYLCKDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PFK_YLBLTL_XFYLCKD", Namespace="http://Thok.WMS.Interface/", Order=0)]
        public Test.MesWebSvr.PFK_YLBLTL_XFYLCKDRequestBody Body;
        
        public PFK_YLBLTL_XFYLCKDRequest() {
        }
        
        public PFK_YLBLTL_XFYLCKDRequest(Test.MesWebSvr.PFK_YLBLTL_XFYLCKDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Thok.WMS.Interface/")]
    public partial class PFK_YLBLTL_XFYLCKDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string movestockXML;
        
        public PFK_YLBLTL_XFYLCKDRequestBody() {
        }
        
        public PFK_YLBLTL_XFYLCKDRequestBody(string movestockXML) {
            this.movestockXML = movestockXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PFK_YLBLTL_XFYLCKDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PFK_YLBLTL_XFYLCKDResponse", Namespace="http://Thok.WMS.Interface/", Order=0)]
        public Test.MesWebSvr.PFK_YLBLTL_XFYLCKDResponseBody Body;
        
        public PFK_YLBLTL_XFYLCKDResponse() {
        }
        
        public PFK_YLBLTL_XFYLCKDResponse(Test.MesWebSvr.PFK_YLBLTL_XFYLCKDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Thok.WMS.Interface/")]
    public partial class PFK_YLBLTL_XFYLCKDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PFK_YLBLTL_XFYLCKDResult;
        
        public PFK_YLBLTL_XFYLCKDResponseBody() {
        }
        
        public PFK_YLBLTL_XFYLCKDResponseBody(string PFK_YLBLTL_XFYLCKDResult) {
            this.PFK_YLBLTL_XFYLCKDResult = PFK_YLBLTL_XFYLCKDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PFK_YLBLTL_XFTLDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PFK_YLBLTL_XFTLD", Namespace="http://Thok.WMS.Interface/", Order=0)]
        public Test.MesWebSvr.PFK_YLBLTL_XFTLDRequestBody Body;
        
        public PFK_YLBLTL_XFTLDRequest() {
        }
        
        public PFK_YLBLTL_XFTLDRequest(Test.MesWebSvr.PFK_YLBLTL_XFTLDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Thok.WMS.Interface/")]
    public partial class PFK_YLBLTL_XFTLDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string backstockXML;
        
        public PFK_YLBLTL_XFTLDRequestBody() {
        }
        
        public PFK_YLBLTL_XFTLDRequestBody(string backstockXML) {
            this.backstockXML = backstockXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PFK_YLBLTL_XFTLDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PFK_YLBLTL_XFTLDResponse", Namespace="http://Thok.WMS.Interface/", Order=0)]
        public Test.MesWebSvr.PFK_YLBLTL_XFTLDResponseBody Body;
        
        public PFK_YLBLTL_XFTLDResponse() {
        }
        
        public PFK_YLBLTL_XFTLDResponse(Test.MesWebSvr.PFK_YLBLTL_XFTLDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Thok.WMS.Interface/")]
    public partial class PFK_YLBLTL_XFTLDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PFK_YLBLTL_XFTLDResult;
        
        public PFK_YLBLTL_XFTLDResponseBody() {
        }
        
        public PFK_YLBLTL_XFTLDResponseBody(string PFK_YLBLTL_XFTLDResult) {
            this.PFK_YLBLTL_XFTLDResult = PFK_YLBLTL_XFTLDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PFK_YLBL_BLCKRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PFK_YLBL_BLCK", Namespace="http://Thok.WMS.Interface/", Order=0)]
        public Test.MesWebSvr.PFK_YLBL_BLCKRequestBody Body;
        
        public PFK_YLBL_BLCKRequest() {
        }
        
        public PFK_YLBL_BLCKRequest(Test.MesWebSvr.PFK_YLBL_BLCKRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Thok.WMS.Interface/")]
    public partial class PFK_YLBL_BLCKRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string materialfeedXML;
        
        public PFK_YLBL_BLCKRequestBody() {
        }
        
        public PFK_YLBL_BLCKRequestBody(string materialfeedXML) {
            this.materialfeedXML = materialfeedXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PFK_YLBL_BLCKResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PFK_YLBL_BLCKResponse", Namespace="http://Thok.WMS.Interface/", Order=0)]
        public Test.MesWebSvr.PFK_YLBL_BLCKResponseBody Body;
        
        public PFK_YLBL_BLCKResponse() {
        }
        
        public PFK_YLBL_BLCKResponse(Test.MesWebSvr.PFK_YLBL_BLCKResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Thok.WMS.Interface/")]
    public partial class PFK_YLBL_BLCKResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PFK_YLBL_BLCKResult;
        
        public PFK_YLBL_BLCKResponseBody() {
        }
        
        public PFK_YLBL_BLCKResponseBody(string PFK_YLBL_BLCKResult) {
            this.PFK_YLBL_BLCKResult = PFK_YLBL_BLCKResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PFK_YLCSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PFK_YLCS", Namespace="http://Thok.WMS.Interface/", Order=0)]
        public Test.MesWebSvr.PFK_YLCSRequestBody Body;
        
        public PFK_YLCSRequest() {
        }
        
        public PFK_YLCSRequest(Test.MesWebSvr.PFK_YLCSRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Thok.WMS.Interface/")]
    public partial class PFK_YLCSRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string estimateparamsXML;
        
        public PFK_YLCSRequestBody() {
        }
        
        public PFK_YLCSRequestBody(string estimateparamsXML) {
            this.estimateparamsXML = estimateparamsXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PFK_YLCSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PFK_YLCSResponse", Namespace="http://Thok.WMS.Interface/", Order=0)]
        public Test.MesWebSvr.PFK_YLCSResponseBody Body;
        
        public PFK_YLCSResponse() {
        }
        
        public PFK_YLCSResponse(Test.MesWebSvr.PFK_YLCSResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Thok.WMS.Interface/")]
    public partial class PFK_YLCSResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PFK_YLCSResult;
        
        public PFK_YLCSResponseBody() {
        }
        
        public PFK_YLCSResponseBody(string PFK_YLCSResult) {
            this.PFK_YLCSResult = PFK_YLCSResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PFK_YLTC_ZSJHRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PFK_YLTC_ZSJH", Namespace="http://Thok.WMS.Interface/", Order=0)]
        public Test.MesWebSvr.PFK_YLTC_ZSJHRequestBody Body;
        
        public PFK_YLTC_ZSJHRequest() {
        }
        
        public PFK_YLTC_ZSJHRequest(Test.MesWebSvr.PFK_YLTC_ZSJHRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Thok.WMS.Interface/")]
    public partial class PFK_YLTC_ZSJHRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string productionplanXML;
        
        public PFK_YLTC_ZSJHRequestBody() {
        }
        
        public PFK_YLTC_ZSJHRequestBody(string productionplanXML) {
            this.productionplanXML = productionplanXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PFK_YLTC_ZSJHResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PFK_YLTC_ZSJHResponse", Namespace="http://Thok.WMS.Interface/", Order=0)]
        public Test.MesWebSvr.PFK_YLTC_ZSJHResponseBody Body;
        
        public PFK_YLTC_ZSJHResponse() {
        }
        
        public PFK_YLTC_ZSJHResponse(Test.MesWebSvr.PFK_YLTC_ZSJHResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Thok.WMS.Interface/")]
    public partial class PFK_YLTC_ZSJHResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PFK_YLTC_ZSJHResult;
        
        public PFK_YLTC_ZSJHResponseBody() {
        }
        
        public PFK_YLTC_ZSJHResponseBody(string PFK_YLTC_ZSJHResult) {
            this.PFK_YLTC_ZSJHResult = PFK_YLTC_ZSJHResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PFK_YLTC_GDXFRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PFK_YLTC_GDXF", Namespace="http://Thok.WMS.Interface/", Order=0)]
        public Test.MesWebSvr.PFK_YLTC_GDXFRequestBody Body;
        
        public PFK_YLTC_GDXFRequest() {
        }
        
        public PFK_YLTC_GDXFRequest(Test.MesWebSvr.PFK_YLTC_GDXFRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Thok.WMS.Interface/")]
    public partial class PFK_YLTC_GDXFRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string stockoutXML;
        
        public PFK_YLTC_GDXFRequestBody() {
        }
        
        public PFK_YLTC_GDXFRequestBody(string stockoutXML) {
            this.stockoutXML = stockoutXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PFK_YLTC_GDXFResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PFK_YLTC_GDXFResponse", Namespace="http://Thok.WMS.Interface/", Order=0)]
        public Test.MesWebSvr.PFK_YLTC_GDXFResponseBody Body;
        
        public PFK_YLTC_GDXFResponse() {
        }
        
        public PFK_YLTC_GDXFResponse(Test.MesWebSvr.PFK_YLTC_GDXFResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Thok.WMS.Interface/")]
    public partial class PFK_YLTC_GDXFResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PFK_YLTC_GDXFResult;
        
        public PFK_YLTC_GDXFResponseBody() {
        }
        
        public PFK_YLTC_GDXFResponseBody(string PFK_YLTC_GDXFResult) {
            this.PFK_YLTC_GDXFResult = PFK_YLTC_GDXFResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PFK_YLTC_GDQXRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PFK_YLTC_GDQX", Namespace="http://Thok.WMS.Interface/", Order=0)]
        public Test.MesWebSvr.PFK_YLTC_GDQXRequestBody Body;
        
        public PFK_YLTC_GDQXRequest() {
        }
        
        public PFK_YLTC_GDQXRequest(Test.MesWebSvr.PFK_YLTC_GDQXRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Thok.WMS.Interface/")]
    public partial class PFK_YLTC_GDQXRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string stockoutcanceXML;
        
        public PFK_YLTC_GDQXRequestBody() {
        }
        
        public PFK_YLTC_GDQXRequestBody(string stockoutcanceXML) {
            this.stockoutcanceXML = stockoutcanceXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PFK_YLTC_GDQXResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PFK_YLTC_GDQXResponse", Namespace="http://Thok.WMS.Interface/", Order=0)]
        public Test.MesWebSvr.PFK_YLTC_GDQXResponseBody Body;
        
        public PFK_YLTC_GDQXResponse() {
        }
        
        public PFK_YLTC_GDQXResponse(Test.MesWebSvr.PFK_YLTC_GDQXResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Thok.WMS.Interface/")]
    public partial class PFK_YLTC_GDQXResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PFK_YLTC_GDQXResult;
        
        public PFK_YLTC_GDQXResponseBody() {
        }
        
        public PFK_YLTC_GDQXResponseBody(string PFK_YLTC_GDQXResult) {
            this.PFK_YLTC_GDQXResult = PFK_YLTC_GDQXResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PFK_KCGX_KCCXRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PFK_KCGX_KCCX", Namespace="http://Thok.WMS.Interface/", Order=0)]
        public Test.MesWebSvr.PFK_KCGX_KCCXRequestBody Body;
        
        public PFK_KCGX_KCCXRequest() {
        }
        
        public PFK_KCGX_KCCXRequest(Test.MesWebSvr.PFK_KCGX_KCCXRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Thok.WMS.Interface/")]
    public partial class PFK_KCGX_KCCXRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string searchparamsXML;
        
        public PFK_KCGX_KCCXRequestBody() {
        }
        
        public PFK_KCGX_KCCXRequestBody(string searchparamsXML) {
            this.searchparamsXML = searchparamsXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PFK_KCGX_KCCXResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PFK_KCGX_KCCXResponse", Namespace="http://Thok.WMS.Interface/", Order=0)]
        public Test.MesWebSvr.PFK_KCGX_KCCXResponseBody Body;
        
        public PFK_KCGX_KCCXResponse() {
        }
        
        public PFK_KCGX_KCCXResponse(Test.MesWebSvr.PFK_KCGX_KCCXResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Thok.WMS.Interface/")]
    public partial class PFK_KCGX_KCCXResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PFK_KCGX_KCCXResult;
        
        public PFK_KCGX_KCCXResponseBody() {
        }
        
        public PFK_KCGX_KCCXResponseBody(string PFK_KCGX_KCCXResult) {
            this.PFK_KCGX_KCCXResult = PFK_KCGX_KCCXResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PFK_KCGX_KGXXRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PFK_KCGX_KGXX", Namespace="http://Thok.WMS.Interface/", Order=0)]
        public Test.MesWebSvr.PFK_KCGX_KGXXRequestBody Body;
        
        public PFK_KCGX_KGXXRequest() {
        }
        
        public PFK_KCGX_KGXXRequest(Test.MesWebSvr.PFK_KCGX_KGXXRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Thok.WMS.Interface/")]
    public partial class PFK_KCGX_KGXXRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string storesourceXML;
        
        public PFK_KCGX_KGXXRequestBody() {
        }
        
        public PFK_KCGX_KGXXRequestBody(string storesourceXML) {
            this.storesourceXML = storesourceXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PFK_KCGX_KGXXResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PFK_KCGX_KGXXResponse", Namespace="http://Thok.WMS.Interface/", Order=0)]
        public Test.MesWebSvr.PFK_KCGX_KGXXResponseBody Body;
        
        public PFK_KCGX_KGXXResponse() {
        }
        
        public PFK_KCGX_KGXXResponse(Test.MesWebSvr.PFK_KCGX_KGXXResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Thok.WMS.Interface/")]
    public partial class PFK_KCGX_KGXXResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PFK_KCGX_KGXXResult;
        
        public PFK_KCGX_KGXXResponseBody() {
        }
        
        public PFK_KCGX_KGXXResponseBody(string PFK_KCGX_KGXXResult) {
            this.PFK_KCGX_KGXXResult = PFK_KCGX_KGXXResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PFK_JCSJ_YYCDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PFK_JCSJ_YYCD", Namespace="http://Thok.WMS.Interface/", Order=0)]
        public Test.MesWebSvr.PFK_JCSJ_YYCDRequestBody Body;
        
        public PFK_JCSJ_YYCDRequest() {
        }
        
        public PFK_JCSJ_YYCDRequest(Test.MesWebSvr.PFK_JCSJ_YYCDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Thok.WMS.Interface/")]
    public partial class PFK_JCSJ_YYCDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string leaforiginalXML;
        
        public PFK_JCSJ_YYCDRequestBody() {
        }
        
        public PFK_JCSJ_YYCDRequestBody(string leaforiginalXML) {
            this.leaforiginalXML = leaforiginalXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PFK_JCSJ_YYCDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PFK_JCSJ_YYCDResponse", Namespace="http://Thok.WMS.Interface/", Order=0)]
        public Test.MesWebSvr.PFK_JCSJ_YYCDResponseBody Body;
        
        public PFK_JCSJ_YYCDResponse() {
        }
        
        public PFK_JCSJ_YYCDResponse(Test.MesWebSvr.PFK_JCSJ_YYCDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Thok.WMS.Interface/")]
    public partial class PFK_JCSJ_YYCDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PFK_JCSJ_YYCDResult;
        
        public PFK_JCSJ_YYCDResponseBody() {
        }
        
        public PFK_JCSJ_YYCDResponseBody(string PFK_JCSJ_YYCDResult) {
            this.PFK_JCSJ_YYCDResult = PFK_JCSJ_YYCDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PFK_JCSJ_YYXTRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PFK_JCSJ_YYXT", Namespace="http://Thok.WMS.Interface/", Order=0)]
        public Test.MesWebSvr.PFK_JCSJ_YYXTRequestBody Body;
        
        public PFK_JCSJ_YYXTRequest() {
        }
        
        public PFK_JCSJ_YYXTRequest(Test.MesWebSvr.PFK_JCSJ_YYXTRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Thok.WMS.Interface/")]
    public partial class PFK_JCSJ_YYXTRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string leafstyleXML;
        
        public PFK_JCSJ_YYXTRequestBody() {
        }
        
        public PFK_JCSJ_YYXTRequestBody(string leafstyleXML) {
            this.leafstyleXML = leafstyleXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PFK_JCSJ_YYXTResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PFK_JCSJ_YYXTResponse", Namespace="http://Thok.WMS.Interface/", Order=0)]
        public Test.MesWebSvr.PFK_JCSJ_YYXTResponseBody Body;
        
        public PFK_JCSJ_YYXTResponse() {
        }
        
        public PFK_JCSJ_YYXTResponse(Test.MesWebSvr.PFK_JCSJ_YYXTResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Thok.WMS.Interface/")]
    public partial class PFK_JCSJ_YYXTResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PFK_JCSJ_YYXTResult;
        
        public PFK_JCSJ_YYXTResponseBody() {
        }
        
        public PFK_JCSJ_YYXTResponseBody(string PFK_JCSJ_YYXTResult) {
            this.PFK_JCSJ_YYXTResult = PFK_JCSJ_YYXTResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PFK_JCSJ_YYLXRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PFK_JCSJ_YYLX", Namespace="http://Thok.WMS.Interface/", Order=0)]
        public Test.MesWebSvr.PFK_JCSJ_YYLXRequestBody Body;
        
        public PFK_JCSJ_YYLXRequest() {
        }
        
        public PFK_JCSJ_YYLXRequest(Test.MesWebSvr.PFK_JCSJ_YYLXRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Thok.WMS.Interface/")]
    public partial class PFK_JCSJ_YYLXRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string leafcategoryXML;
        
        public PFK_JCSJ_YYLXRequestBody() {
        }
        
        public PFK_JCSJ_YYLXRequestBody(string leafcategoryXML) {
            this.leafcategoryXML = leafcategoryXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PFK_JCSJ_YYLXResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PFK_JCSJ_YYLXResponse", Namespace="http://Thok.WMS.Interface/", Order=0)]
        public Test.MesWebSvr.PFK_JCSJ_YYLXResponseBody Body;
        
        public PFK_JCSJ_YYLXResponse() {
        }
        
        public PFK_JCSJ_YYLXResponse(Test.MesWebSvr.PFK_JCSJ_YYLXResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Thok.WMS.Interface/")]
    public partial class PFK_JCSJ_YYLXResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PFK_JCSJ_YYLXResult;
        
        public PFK_JCSJ_YYLXResponseBody() {
        }
        
        public PFK_JCSJ_YYLXResponseBody(string PFK_JCSJ_YYLXResult) {
            this.PFK_JCSJ_YYLXResult = PFK_JCSJ_YYLXResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PFK_JCSJ_YYDJRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PFK_JCSJ_YYDJ", Namespace="http://Thok.WMS.Interface/", Order=0)]
        public Test.MesWebSvr.PFK_JCSJ_YYDJRequestBody Body;
        
        public PFK_JCSJ_YYDJRequest() {
        }
        
        public PFK_JCSJ_YYDJRequest(Test.MesWebSvr.PFK_JCSJ_YYDJRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Thok.WMS.Interface/")]
    public partial class PFK_JCSJ_YYDJRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string leafgradeXML;
        
        public PFK_JCSJ_YYDJRequestBody() {
        }
        
        public PFK_JCSJ_YYDJRequestBody(string leafgradeXML) {
            this.leafgradeXML = leafgradeXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PFK_JCSJ_YYDJResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PFK_JCSJ_YYDJResponse", Namespace="http://Thok.WMS.Interface/", Order=0)]
        public Test.MesWebSvr.PFK_JCSJ_YYDJResponseBody Body;
        
        public PFK_JCSJ_YYDJResponse() {
        }
        
        public PFK_JCSJ_YYDJResponse(Test.MesWebSvr.PFK_JCSJ_YYDJResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Thok.WMS.Interface/")]
    public partial class PFK_JCSJ_YYDJResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PFK_JCSJ_YYDJResult;
        
        public PFK_JCSJ_YYDJResponseBody() {
        }
        
        public PFK_JCSJ_YYDJResponseBody(string PFK_JCSJ_YYDJResult) {
            this.PFK_JCSJ_YYDJResult = PFK_JCSJ_YYDJResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PFK_JCSJ_YYRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PFK_JCSJ_YY", Namespace="http://Thok.WMS.Interface/", Order=0)]
        public Test.MesWebSvr.PFK_JCSJ_YYRequestBody Body;
        
        public PFK_JCSJ_YYRequest() {
        }
        
        public PFK_JCSJ_YYRequest(Test.MesWebSvr.PFK_JCSJ_YYRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Thok.WMS.Interface/")]
    public partial class PFK_JCSJ_YYRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string leafXML;
        
        public PFK_JCSJ_YYRequestBody() {
        }
        
        public PFK_JCSJ_YYRequestBody(string leafXML) {
            this.leafXML = leafXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PFK_JCSJ_YYResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PFK_JCSJ_YYResponse", Namespace="http://Thok.WMS.Interface/", Order=0)]
        public Test.MesWebSvr.PFK_JCSJ_YYResponseBody Body;
        
        public PFK_JCSJ_YYResponse() {
        }
        
        public PFK_JCSJ_YYResponse(Test.MesWebSvr.PFK_JCSJ_YYResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Thok.WMS.Interface/")]
    public partial class PFK_JCSJ_YYResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PFK_JCSJ_YYResult;
        
        public PFK_JCSJ_YYResponseBody() {
        }
        
        public PFK_JCSJ_YYResponseBody(string PFK_JCSJ_YYResult) {
            this.PFK_JCSJ_YYResult = PFK_JCSJ_YYResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PFK_JCSJ_YSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PFK_JCSJ_YS", Namespace="http://Thok.WMS.Interface/", Order=0)]
        public Test.MesWebSvr.PFK_JCSJ_YSRequestBody Body;
        
        public PFK_JCSJ_YSRequest() {
        }
        
        public PFK_JCSJ_YSRequest(Test.MesWebSvr.PFK_JCSJ_YSRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Thok.WMS.Interface/")]
    public partial class PFK_JCSJ_YSRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string tobXML;
        
        public PFK_JCSJ_YSRequestBody() {
        }
        
        public PFK_JCSJ_YSRequestBody(string tobXML) {
            this.tobXML = tobXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PFK_JCSJ_YSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PFK_JCSJ_YSResponse", Namespace="http://Thok.WMS.Interface/", Order=0)]
        public Test.MesWebSvr.PFK_JCSJ_YSResponseBody Body;
        
        public PFK_JCSJ_YSResponse() {
        }
        
        public PFK_JCSJ_YSResponse(Test.MesWebSvr.PFK_JCSJ_YSResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Thok.WMS.Interface/")]
    public partial class PFK_JCSJ_YSResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PFK_JCSJ_YSResult;
        
        public PFK_JCSJ_YSResponseBody() {
        }
        
        public PFK_JCSJ_YSResponseBody(string PFK_JCSJ_YSResult) {
            this.PFK_JCSJ_YSResult = PFK_JCSJ_YSResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AHZY_ESB_WMS_TRANSSVSoapChannel : Test.MesWebSvr.AHZY_ESB_WMS_TRANSSVSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AHZY_ESB_WMS_TRANSSVSoapClient : System.ServiceModel.ClientBase<Test.MesWebSvr.AHZY_ESB_WMS_TRANSSVSoap>, Test.MesWebSvr.AHZY_ESB_WMS_TRANSSVSoap {
        
        public AHZY_ESB_WMS_TRANSSVSoapClient() {
        }
        
        public AHZY_ESB_WMS_TRANSSVSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AHZY_ESB_WMS_TRANSSVSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AHZY_ESB_WMS_TRANSSVSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AHZY_ESB_WMS_TRANSSVSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Test.MesWebSvr.PFK_YZPF_PFXDResponse Test.MesWebSvr.AHZY_ESB_WMS_TRANSSVSoap.PFK_YZPF_PFXD(Test.MesWebSvr.PFK_YZPF_PFXDRequest request) {
            return base.Channel.PFK_YZPF_PFXD(request);
        }
        
        public string PFK_YZPF_PFXD(string bominfoXML) {
            Test.MesWebSvr.PFK_YZPF_PFXDRequest inValue = new Test.MesWebSvr.PFK_YZPF_PFXDRequest();
            inValue.Body = new Test.MesWebSvr.PFK_YZPF_PFXDRequestBody();
            inValue.Body.bominfoXML = bominfoXML;
            Test.MesWebSvr.PFK_YZPF_PFXDResponse retVal = ((Test.MesWebSvr.AHZY_ESB_WMS_TRANSSVSoap)(this)).PFK_YZPF_PFXD(inValue);
            return retVal.Body.PFK_YZPF_PFXDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Test.MesWebSvr.PFK_YZPF_PFFZResponse Test.MesWebSvr.AHZY_ESB_WMS_TRANSSVSoap.PFK_YZPF_PFFZ(Test.MesWebSvr.PFK_YZPF_PFFZRequest request) {
            return base.Channel.PFK_YZPF_PFFZ(request);
        }
        
        public string PFK_YZPF_PFFZ(string abolishinfoXML) {
            Test.MesWebSvr.PFK_YZPF_PFFZRequest inValue = new Test.MesWebSvr.PFK_YZPF_PFFZRequest();
            inValue.Body = new Test.MesWebSvr.PFK_YZPF_PFFZRequestBody();
            inValue.Body.abolishinfoXML = abolishinfoXML;
            Test.MesWebSvr.PFK_YZPF_PFFZResponse retVal = ((Test.MesWebSvr.AHZY_ESB_WMS_TRANSSVSoap)(this)).PFK_YZPF_PFFZ(inValue);
            return retVal.Body.PFK_YZPF_PFFZResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Test.MesWebSvr.PFK_YLBLTL_XFZSBLJHResponse Test.MesWebSvr.AHZY_ESB_WMS_TRANSSVSoap.PFK_YLBLTL_XFZSBLJH(Test.MesWebSvr.PFK_YLBLTL_XFZSBLJHRequest request) {
            return base.Channel.PFK_YLBLTL_XFZSBLJH(request);
        }
        
        public string PFK_YLBLTL_XFZSBLJH(string prepareplanXML) {
            Test.MesWebSvr.PFK_YLBLTL_XFZSBLJHRequest inValue = new Test.MesWebSvr.PFK_YLBLTL_XFZSBLJHRequest();
            inValue.Body = new Test.MesWebSvr.PFK_YLBLTL_XFZSBLJHRequestBody();
            inValue.Body.prepareplanXML = prepareplanXML;
            Test.MesWebSvr.PFK_YLBLTL_XFZSBLJHResponse retVal = ((Test.MesWebSvr.AHZY_ESB_WMS_TRANSSVSoap)(this)).PFK_YLBLTL_XFZSBLJH(inValue);
            return retVal.Body.PFK_YLBLTL_XFZSBLJHResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Test.MesWebSvr.PFK_YLBLTL_XFYLCKDResponse Test.MesWebSvr.AHZY_ESB_WMS_TRANSSVSoap.PFK_YLBLTL_XFYLCKD(Test.MesWebSvr.PFK_YLBLTL_XFYLCKDRequest request) {
            return base.Channel.PFK_YLBLTL_XFYLCKD(request);
        }
        
        public string PFK_YLBLTL_XFYLCKD(string movestockXML) {
            Test.MesWebSvr.PFK_YLBLTL_XFYLCKDRequest inValue = new Test.MesWebSvr.PFK_YLBLTL_XFYLCKDRequest();
            inValue.Body = new Test.MesWebSvr.PFK_YLBLTL_XFYLCKDRequestBody();
            inValue.Body.movestockXML = movestockXML;
            Test.MesWebSvr.PFK_YLBLTL_XFYLCKDResponse retVal = ((Test.MesWebSvr.AHZY_ESB_WMS_TRANSSVSoap)(this)).PFK_YLBLTL_XFYLCKD(inValue);
            return retVal.Body.PFK_YLBLTL_XFYLCKDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Test.MesWebSvr.PFK_YLBLTL_XFTLDResponse Test.MesWebSvr.AHZY_ESB_WMS_TRANSSVSoap.PFK_YLBLTL_XFTLD(Test.MesWebSvr.PFK_YLBLTL_XFTLDRequest request) {
            return base.Channel.PFK_YLBLTL_XFTLD(request);
        }
        
        public string PFK_YLBLTL_XFTLD(string backstockXML) {
            Test.MesWebSvr.PFK_YLBLTL_XFTLDRequest inValue = new Test.MesWebSvr.PFK_YLBLTL_XFTLDRequest();
            inValue.Body = new Test.MesWebSvr.PFK_YLBLTL_XFTLDRequestBody();
            inValue.Body.backstockXML = backstockXML;
            Test.MesWebSvr.PFK_YLBLTL_XFTLDResponse retVal = ((Test.MesWebSvr.AHZY_ESB_WMS_TRANSSVSoap)(this)).PFK_YLBLTL_XFTLD(inValue);
            return retVal.Body.PFK_YLBLTL_XFTLDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Test.MesWebSvr.PFK_YLBL_BLCKResponse Test.MesWebSvr.AHZY_ESB_WMS_TRANSSVSoap.PFK_YLBL_BLCK(Test.MesWebSvr.PFK_YLBL_BLCKRequest request) {
            return base.Channel.PFK_YLBL_BLCK(request);
        }
        
        public string PFK_YLBL_BLCK(string materialfeedXML) {
            Test.MesWebSvr.PFK_YLBL_BLCKRequest inValue = new Test.MesWebSvr.PFK_YLBL_BLCKRequest();
            inValue.Body = new Test.MesWebSvr.PFK_YLBL_BLCKRequestBody();
            inValue.Body.materialfeedXML = materialfeedXML;
            Test.MesWebSvr.PFK_YLBL_BLCKResponse retVal = ((Test.MesWebSvr.AHZY_ESB_WMS_TRANSSVSoap)(this)).PFK_YLBL_BLCK(inValue);
            return retVal.Body.PFK_YLBL_BLCKResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Test.MesWebSvr.PFK_YLCSResponse Test.MesWebSvr.AHZY_ESB_WMS_TRANSSVSoap.PFK_YLCS(Test.MesWebSvr.PFK_YLCSRequest request) {
            return base.Channel.PFK_YLCS(request);
        }
        
        public string PFK_YLCS(string estimateparamsXML) {
            Test.MesWebSvr.PFK_YLCSRequest inValue = new Test.MesWebSvr.PFK_YLCSRequest();
            inValue.Body = new Test.MesWebSvr.PFK_YLCSRequestBody();
            inValue.Body.estimateparamsXML = estimateparamsXML;
            Test.MesWebSvr.PFK_YLCSResponse retVal = ((Test.MesWebSvr.AHZY_ESB_WMS_TRANSSVSoap)(this)).PFK_YLCS(inValue);
            return retVal.Body.PFK_YLCSResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Test.MesWebSvr.PFK_YLTC_ZSJHResponse Test.MesWebSvr.AHZY_ESB_WMS_TRANSSVSoap.PFK_YLTC_ZSJH(Test.MesWebSvr.PFK_YLTC_ZSJHRequest request) {
            return base.Channel.PFK_YLTC_ZSJH(request);
        }
        
        public string PFK_YLTC_ZSJH(string productionplanXML) {
            Test.MesWebSvr.PFK_YLTC_ZSJHRequest inValue = new Test.MesWebSvr.PFK_YLTC_ZSJHRequest();
            inValue.Body = new Test.MesWebSvr.PFK_YLTC_ZSJHRequestBody();
            inValue.Body.productionplanXML = productionplanXML;
            Test.MesWebSvr.PFK_YLTC_ZSJHResponse retVal = ((Test.MesWebSvr.AHZY_ESB_WMS_TRANSSVSoap)(this)).PFK_YLTC_ZSJH(inValue);
            return retVal.Body.PFK_YLTC_ZSJHResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Test.MesWebSvr.PFK_YLTC_GDXFResponse Test.MesWebSvr.AHZY_ESB_WMS_TRANSSVSoap.PFK_YLTC_GDXF(Test.MesWebSvr.PFK_YLTC_GDXFRequest request) {
            return base.Channel.PFK_YLTC_GDXF(request);
        }
        
        public string PFK_YLTC_GDXF(string stockoutXML) {
            Test.MesWebSvr.PFK_YLTC_GDXFRequest inValue = new Test.MesWebSvr.PFK_YLTC_GDXFRequest();
            inValue.Body = new Test.MesWebSvr.PFK_YLTC_GDXFRequestBody();
            inValue.Body.stockoutXML = stockoutXML;
            Test.MesWebSvr.PFK_YLTC_GDXFResponse retVal = ((Test.MesWebSvr.AHZY_ESB_WMS_TRANSSVSoap)(this)).PFK_YLTC_GDXF(inValue);
            return retVal.Body.PFK_YLTC_GDXFResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Test.MesWebSvr.PFK_YLTC_GDQXResponse Test.MesWebSvr.AHZY_ESB_WMS_TRANSSVSoap.PFK_YLTC_GDQX(Test.MesWebSvr.PFK_YLTC_GDQXRequest request) {
            return base.Channel.PFK_YLTC_GDQX(request);
        }
        
        public string PFK_YLTC_GDQX(string stockoutcanceXML) {
            Test.MesWebSvr.PFK_YLTC_GDQXRequest inValue = new Test.MesWebSvr.PFK_YLTC_GDQXRequest();
            inValue.Body = new Test.MesWebSvr.PFK_YLTC_GDQXRequestBody();
            inValue.Body.stockoutcanceXML = stockoutcanceXML;
            Test.MesWebSvr.PFK_YLTC_GDQXResponse retVal = ((Test.MesWebSvr.AHZY_ESB_WMS_TRANSSVSoap)(this)).PFK_YLTC_GDQX(inValue);
            return retVal.Body.PFK_YLTC_GDQXResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Test.MesWebSvr.PFK_KCGX_KCCXResponse Test.MesWebSvr.AHZY_ESB_WMS_TRANSSVSoap.PFK_KCGX_KCCX(Test.MesWebSvr.PFK_KCGX_KCCXRequest request) {
            return base.Channel.PFK_KCGX_KCCX(request);
        }
        
        public string PFK_KCGX_KCCX(string searchparamsXML) {
            Test.MesWebSvr.PFK_KCGX_KCCXRequest inValue = new Test.MesWebSvr.PFK_KCGX_KCCXRequest();
            inValue.Body = new Test.MesWebSvr.PFK_KCGX_KCCXRequestBody();
            inValue.Body.searchparamsXML = searchparamsXML;
            Test.MesWebSvr.PFK_KCGX_KCCXResponse retVal = ((Test.MesWebSvr.AHZY_ESB_WMS_TRANSSVSoap)(this)).PFK_KCGX_KCCX(inValue);
            return retVal.Body.PFK_KCGX_KCCXResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Test.MesWebSvr.PFK_KCGX_KGXXResponse Test.MesWebSvr.AHZY_ESB_WMS_TRANSSVSoap.PFK_KCGX_KGXX(Test.MesWebSvr.PFK_KCGX_KGXXRequest request) {
            return base.Channel.PFK_KCGX_KGXX(request);
        }
        
        public string PFK_KCGX_KGXX(string storesourceXML) {
            Test.MesWebSvr.PFK_KCGX_KGXXRequest inValue = new Test.MesWebSvr.PFK_KCGX_KGXXRequest();
            inValue.Body = new Test.MesWebSvr.PFK_KCGX_KGXXRequestBody();
            inValue.Body.storesourceXML = storesourceXML;
            Test.MesWebSvr.PFK_KCGX_KGXXResponse retVal = ((Test.MesWebSvr.AHZY_ESB_WMS_TRANSSVSoap)(this)).PFK_KCGX_KGXX(inValue);
            return retVal.Body.PFK_KCGX_KGXXResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Test.MesWebSvr.PFK_JCSJ_YYCDResponse Test.MesWebSvr.AHZY_ESB_WMS_TRANSSVSoap.PFK_JCSJ_YYCD(Test.MesWebSvr.PFK_JCSJ_YYCDRequest request) {
            return base.Channel.PFK_JCSJ_YYCD(request);
        }
        
        public string PFK_JCSJ_YYCD(string leaforiginalXML) {
            Test.MesWebSvr.PFK_JCSJ_YYCDRequest inValue = new Test.MesWebSvr.PFK_JCSJ_YYCDRequest();
            inValue.Body = new Test.MesWebSvr.PFK_JCSJ_YYCDRequestBody();
            inValue.Body.leaforiginalXML = leaforiginalXML;
            Test.MesWebSvr.PFK_JCSJ_YYCDResponse retVal = ((Test.MesWebSvr.AHZY_ESB_WMS_TRANSSVSoap)(this)).PFK_JCSJ_YYCD(inValue);
            return retVal.Body.PFK_JCSJ_YYCDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Test.MesWebSvr.PFK_JCSJ_YYXTResponse Test.MesWebSvr.AHZY_ESB_WMS_TRANSSVSoap.PFK_JCSJ_YYXT(Test.MesWebSvr.PFK_JCSJ_YYXTRequest request) {
            return base.Channel.PFK_JCSJ_YYXT(request);
        }
        
        public string PFK_JCSJ_YYXT(string leafstyleXML) {
            Test.MesWebSvr.PFK_JCSJ_YYXTRequest inValue = new Test.MesWebSvr.PFK_JCSJ_YYXTRequest();
            inValue.Body = new Test.MesWebSvr.PFK_JCSJ_YYXTRequestBody();
            inValue.Body.leafstyleXML = leafstyleXML;
            Test.MesWebSvr.PFK_JCSJ_YYXTResponse retVal = ((Test.MesWebSvr.AHZY_ESB_WMS_TRANSSVSoap)(this)).PFK_JCSJ_YYXT(inValue);
            return retVal.Body.PFK_JCSJ_YYXTResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Test.MesWebSvr.PFK_JCSJ_YYLXResponse Test.MesWebSvr.AHZY_ESB_WMS_TRANSSVSoap.PFK_JCSJ_YYLX(Test.MesWebSvr.PFK_JCSJ_YYLXRequest request) {
            return base.Channel.PFK_JCSJ_YYLX(request);
        }
        
        public string PFK_JCSJ_YYLX(string leafcategoryXML) {
            Test.MesWebSvr.PFK_JCSJ_YYLXRequest inValue = new Test.MesWebSvr.PFK_JCSJ_YYLXRequest();
            inValue.Body = new Test.MesWebSvr.PFK_JCSJ_YYLXRequestBody();
            inValue.Body.leafcategoryXML = leafcategoryXML;
            Test.MesWebSvr.PFK_JCSJ_YYLXResponse retVal = ((Test.MesWebSvr.AHZY_ESB_WMS_TRANSSVSoap)(this)).PFK_JCSJ_YYLX(inValue);
            return retVal.Body.PFK_JCSJ_YYLXResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Test.MesWebSvr.PFK_JCSJ_YYDJResponse Test.MesWebSvr.AHZY_ESB_WMS_TRANSSVSoap.PFK_JCSJ_YYDJ(Test.MesWebSvr.PFK_JCSJ_YYDJRequest request) {
            return base.Channel.PFK_JCSJ_YYDJ(request);
        }
        
        public string PFK_JCSJ_YYDJ(string leafgradeXML) {
            Test.MesWebSvr.PFK_JCSJ_YYDJRequest inValue = new Test.MesWebSvr.PFK_JCSJ_YYDJRequest();
            inValue.Body = new Test.MesWebSvr.PFK_JCSJ_YYDJRequestBody();
            inValue.Body.leafgradeXML = leafgradeXML;
            Test.MesWebSvr.PFK_JCSJ_YYDJResponse retVal = ((Test.MesWebSvr.AHZY_ESB_WMS_TRANSSVSoap)(this)).PFK_JCSJ_YYDJ(inValue);
            return retVal.Body.PFK_JCSJ_YYDJResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Test.MesWebSvr.PFK_JCSJ_YYResponse Test.MesWebSvr.AHZY_ESB_WMS_TRANSSVSoap.PFK_JCSJ_YY(Test.MesWebSvr.PFK_JCSJ_YYRequest request) {
            return base.Channel.PFK_JCSJ_YY(request);
        }
        
        public string PFK_JCSJ_YY(string leafXML) {
            Test.MesWebSvr.PFK_JCSJ_YYRequest inValue = new Test.MesWebSvr.PFK_JCSJ_YYRequest();
            inValue.Body = new Test.MesWebSvr.PFK_JCSJ_YYRequestBody();
            inValue.Body.leafXML = leafXML;
            Test.MesWebSvr.PFK_JCSJ_YYResponse retVal = ((Test.MesWebSvr.AHZY_ESB_WMS_TRANSSVSoap)(this)).PFK_JCSJ_YY(inValue);
            return retVal.Body.PFK_JCSJ_YYResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Test.MesWebSvr.PFK_JCSJ_YSResponse Test.MesWebSvr.AHZY_ESB_WMS_TRANSSVSoap.PFK_JCSJ_YS(Test.MesWebSvr.PFK_JCSJ_YSRequest request) {
            return base.Channel.PFK_JCSJ_YS(request);
        }
        
        public string PFK_JCSJ_YS(string tobXML) {
            Test.MesWebSvr.PFK_JCSJ_YSRequest inValue = new Test.MesWebSvr.PFK_JCSJ_YSRequest();
            inValue.Body = new Test.MesWebSvr.PFK_JCSJ_YSRequestBody();
            inValue.Body.tobXML = tobXML;
            Test.MesWebSvr.PFK_JCSJ_YSResponse retVal = ((Test.MesWebSvr.AHZY_ESB_WMS_TRANSSVSoap)(this)).PFK_JCSJ_YS(inValue);
            return retVal.Body.PFK_JCSJ_YSResult;
        }
    }
}
