//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.AsrsWebSvr {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Thok.WMS.Interface/", ConfigurationName="AsrsWebSvr.AHZY_ESB_WMS_GETSSVSoap")]
    public interface AHZY_ESB_WMS_GETSSVSoap {
        
        // CODEGEN: Generating message contract since element name BillNo from namespace http://Thok.WMS.Interface/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Thok.WMS.Interface/HelloWorld", ReplyAction="*")]
        Test.AsrsWebSvr.HelloWorldResponse HelloWorld(Test.AsrsWebSvr.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name BillNo from namespace http://Thok.WMS.Interface/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Thok.WMS.Interface/StockinFinish", ReplyAction="*")]
        Test.AsrsWebSvr.StockinFinishResponse StockinFinish(Test.AsrsWebSvr.StockinFinishRequest request);
        
        // CODEGEN: Generating message contract since element name BillNo from namespace http://Thok.WMS.Interface/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Thok.WMS.Interface/StockbackFinish", ReplyAction="*")]
        Test.AsrsWebSvr.StockbackFinishResponse StockbackFinish(Test.AsrsWebSvr.StockbackFinishRequest request);
        
        // CODEGEN: Generating message contract since element name BillNo from namespace http://Thok.WMS.Interface/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Thok.WMS.Interface/FeedFinish", ReplyAction="*")]
        Test.AsrsWebSvr.FeedFinishResponse FeedFinish(Test.AsrsWebSvr.FeedFinishRequest request);
        
        // CODEGEN: Generating message contract since element name BillNo from namespace http://Thok.WMS.Interface/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Thok.WMS.Interface/StockOutBegin", ReplyAction="*")]
        Test.AsrsWebSvr.StockOutBeginResponse StockOutBegin(Test.AsrsWebSvr.StockOutBeginRequest request);
        
        // CODEGEN: Generating message contract since element name BillNo from namespace http://Thok.WMS.Interface/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Thok.WMS.Interface/StockOutEnd", ReplyAction="*")]
        Test.AsrsWebSvr.StockOutEndResponse StockOutEnd(Test.AsrsWebSvr.StockOutEndRequest request);
        
        // CODEGEN: Generating message contract since element name BillNo from namespace http://Thok.WMS.Interface/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Thok.WMS.Interface/StockOutCollection", ReplyAction="*")]
        Test.AsrsWebSvr.StockOutCollectionResponse StockOutCollection(Test.AsrsWebSvr.StockOutCollectionRequest request);
        
        // CODEGEN: Generating message contract since element name BillNo from namespace http://Thok.WMS.Interface/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Thok.WMS.Interface/FeedingReplace", ReplyAction="*")]
        Test.AsrsWebSvr.FeedingReplaceResponse FeedingReplace(Test.AsrsWebSvr.FeedingReplaceRequest request);
        
        // CODEGEN: Generating message contract since element name channel_no from namespace http://Thok.WMS.Interface/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Thok.WMS.Interface/OutStockbillreplace", ReplyAction="*")]
        Test.AsrsWebSvr.OutStockbillreplaceResponse OutStockbillreplace(Test.AsrsWebSvr.OutStockbillreplaceRequest request);
        
        // CODEGEN: Generating message contract since element name BillNo from namespace http://Thok.WMS.Interface/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Thok.WMS.Interface/OutStockbilcance", ReplyAction="*")]
        Test.AsrsWebSvr.OutStockbilcanceResponse OutStockbilcance(Test.AsrsWebSvr.OutStockbilcanceRequest request);
        
        // CODEGEN: Generating message contract since element name BillNo from namespace http://Thok.WMS.Interface/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Thok.WMS.Interface/OpenCollection", ReplyAction="*")]
        Test.AsrsWebSvr.OpenCollectionResponse OpenCollection(Test.AsrsWebSvr.OpenCollectionRequest request);
        
        // CODEGEN: Generating message contract since element name BillNo from namespace http://Thok.WMS.Interface/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Thok.WMS.Interface/OpenBegin", ReplyAction="*")]
        Test.AsrsWebSvr.OpenBeginResponse OpenBegin(Test.AsrsWebSvr.OpenBeginRequest request);
        
        // CODEGEN: Generating message contract since element name BillNo from namespace http://Thok.WMS.Interface/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Thok.WMS.Interface/OpenEnd", ReplyAction="*")]
        Test.AsrsWebSvr.OpenEndResponse OpenEnd(Test.AsrsWebSvr.OpenEndRequest request);
        
        // CODEGEN: Generating message contract since element name BillNo from namespace http://Thok.WMS.Interface/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Thok.WMS.Interface/FeedingSend", ReplyAction="*")]
        Test.AsrsWebSvr.FeedingSendResponse FeedingSend(Test.AsrsWebSvr.FeedingSendRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://Thok.WMS.Interface/", Order=0)]
        public Test.AsrsWebSvr.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(Test.AsrsWebSvr.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Thok.WMS.Interface/")]
    public partial class HelloWorldRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string BillNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string billtype;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string finishdate;
        
        public HelloWorldRequestBody() {
        }
        
        public HelloWorldRequestBody(string BillNo, string billtype, string finishdate) {
            this.BillNo = BillNo;
            this.billtype = billtype;
            this.finishdate = finishdate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://Thok.WMS.Interface/", Order=0)]
        public Test.AsrsWebSvr.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(Test.AsrsWebSvr.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Thok.WMS.Interface/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StockinFinishRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="StockinFinish", Namespace="http://Thok.WMS.Interface/", Order=0)]
        public Test.AsrsWebSvr.StockinFinishRequestBody Body;
        
        public StockinFinishRequest() {
        }
        
        public StockinFinishRequest(Test.AsrsWebSvr.StockinFinishRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Thok.WMS.Interface/")]
    public partial class StockinFinishRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string BillNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string billtype;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string finishdate;
        
        public StockinFinishRequestBody() {
        }
        
        public StockinFinishRequestBody(string BillNo, string billtype, string finishdate) {
            this.BillNo = BillNo;
            this.billtype = billtype;
            this.finishdate = finishdate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StockinFinishResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="StockinFinishResponse", Namespace="http://Thok.WMS.Interface/", Order=0)]
        public Test.AsrsWebSvr.StockinFinishResponseBody Body;
        
        public StockinFinishResponse() {
        }
        
        public StockinFinishResponse(Test.AsrsWebSvr.StockinFinishResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Thok.WMS.Interface/")]
    public partial class StockinFinishResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string StockinFinishResult;
        
        public StockinFinishResponseBody() {
        }
        
        public StockinFinishResponseBody(string StockinFinishResult) {
            this.StockinFinishResult = StockinFinishResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StockbackFinishRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="StockbackFinish", Namespace="http://Thok.WMS.Interface/", Order=0)]
        public Test.AsrsWebSvr.StockbackFinishRequestBody Body;
        
        public StockbackFinishRequest() {
        }
        
        public StockbackFinishRequest(Test.AsrsWebSvr.StockbackFinishRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Thok.WMS.Interface/")]
    public partial class StockbackFinishRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string BillNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string billtype;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string finishdate;
        
        public StockbackFinishRequestBody() {
        }
        
        public StockbackFinishRequestBody(string BillNo, string billtype, string finishdate) {
            this.BillNo = BillNo;
            this.billtype = billtype;
            this.finishdate = finishdate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StockbackFinishResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="StockbackFinishResponse", Namespace="http://Thok.WMS.Interface/", Order=0)]
        public Test.AsrsWebSvr.StockbackFinishResponseBody Body;
        
        public StockbackFinishResponse() {
        }
        
        public StockbackFinishResponse(Test.AsrsWebSvr.StockbackFinishResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Thok.WMS.Interface/")]
    public partial class StockbackFinishResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string StockbackFinishResult;
        
        public StockbackFinishResponseBody() {
        }
        
        public StockbackFinishResponseBody(string StockbackFinishResult) {
            this.StockbackFinishResult = StockbackFinishResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FeedFinishRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FeedFinish", Namespace="http://Thok.WMS.Interface/", Order=0)]
        public Test.AsrsWebSvr.FeedFinishRequestBody Body;
        
        public FeedFinishRequest() {
        }
        
        public FeedFinishRequest(Test.AsrsWebSvr.FeedFinishRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Thok.WMS.Interface/")]
    public partial class FeedFinishRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string BillNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string billtype;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string finishdate;
        
        public FeedFinishRequestBody() {
        }
        
        public FeedFinishRequestBody(string BillNo, string billtype, string finishdate) {
            this.BillNo = BillNo;
            this.billtype = billtype;
            this.finishdate = finishdate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FeedFinishResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FeedFinishResponse", Namespace="http://Thok.WMS.Interface/", Order=0)]
        public Test.AsrsWebSvr.FeedFinishResponseBody Body;
        
        public FeedFinishResponse() {
        }
        
        public FeedFinishResponse(Test.AsrsWebSvr.FeedFinishResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Thok.WMS.Interface/")]
    public partial class FeedFinishResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string FeedFinishResult;
        
        public FeedFinishResponseBody() {
        }
        
        public FeedFinishResponseBody(string FeedFinishResult) {
            this.FeedFinishResult = FeedFinishResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StockOutBeginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="StockOutBegin", Namespace="http://Thok.WMS.Interface/", Order=0)]
        public Test.AsrsWebSvr.StockOutBeginRequestBody Body;
        
        public StockOutBeginRequest() {
        }
        
        public StockOutBeginRequest(Test.AsrsWebSvr.StockOutBeginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Thok.WMS.Interface/")]
    public partial class StockOutBeginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string BillNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string State;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Startime;
        
        public StockOutBeginRequestBody() {
        }
        
        public StockOutBeginRequestBody(string BillNo, string State, string Startime) {
            this.BillNo = BillNo;
            this.State = State;
            this.Startime = Startime;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StockOutBeginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="StockOutBeginResponse", Namespace="http://Thok.WMS.Interface/", Order=0)]
        public Test.AsrsWebSvr.StockOutBeginResponseBody Body;
        
        public StockOutBeginResponse() {
        }
        
        public StockOutBeginResponse(Test.AsrsWebSvr.StockOutBeginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Thok.WMS.Interface/")]
    public partial class StockOutBeginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string StockOutBeginResult;
        
        public StockOutBeginResponseBody() {
        }
        
        public StockOutBeginResponseBody(string StockOutBeginResult) {
            this.StockOutBeginResult = StockOutBeginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StockOutEndRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="StockOutEnd", Namespace="http://Thok.WMS.Interface/", Order=0)]
        public Test.AsrsWebSvr.StockOutEndRequestBody Body;
        
        public StockOutEndRequest() {
        }
        
        public StockOutEndRequest(Test.AsrsWebSvr.StockOutEndRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Thok.WMS.Interface/")]
    public partial class StockOutEndRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string BillNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string State;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Endtime;
        
        public StockOutEndRequestBody() {
        }
        
        public StockOutEndRequestBody(string BillNo, string State, string Endtime) {
            this.BillNo = BillNo;
            this.State = State;
            this.Endtime = Endtime;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StockOutEndResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="StockOutEndResponse", Namespace="http://Thok.WMS.Interface/", Order=0)]
        public Test.AsrsWebSvr.StockOutEndResponseBody Body;
        
        public StockOutEndResponse() {
        }
        
        public StockOutEndResponse(Test.AsrsWebSvr.StockOutEndResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Thok.WMS.Interface/")]
    public partial class StockOutEndResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string StockOutEndResult;
        
        public StockOutEndResponseBody() {
        }
        
        public StockOutEndResponseBody(string StockOutEndResult) {
            this.StockOutEndResult = StockOutEndResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StockOutCollectionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="StockOutCollection", Namespace="http://Thok.WMS.Interface/", Order=0)]
        public Test.AsrsWebSvr.StockOutCollectionRequestBody Body;
        
        public StockOutCollectionRequest() {
        }
        
        public StockOutCollectionRequest(Test.AsrsWebSvr.StockOutCollectionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Thok.WMS.Interface/")]
    public partial class StockOutCollectionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string BillNo;
        
        public StockOutCollectionRequestBody() {
        }
        
        public StockOutCollectionRequestBody(string BillNo) {
            this.BillNo = BillNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StockOutCollectionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="StockOutCollectionResponse", Namespace="http://Thok.WMS.Interface/", Order=0)]
        public Test.AsrsWebSvr.StockOutCollectionResponseBody Body;
        
        public StockOutCollectionResponse() {
        }
        
        public StockOutCollectionResponse(Test.AsrsWebSvr.StockOutCollectionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Thok.WMS.Interface/")]
    public partial class StockOutCollectionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string StockOutCollectionResult;
        
        public StockOutCollectionResponseBody() {
        }
        
        public StockOutCollectionResponseBody(string StockOutCollectionResult) {
            this.StockOutCollectionResult = StockOutCollectionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FeedingReplaceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FeedingReplace", Namespace="http://Thok.WMS.Interface/", Order=0)]
        public Test.AsrsWebSvr.FeedingReplaceRequestBody Body;
        
        public FeedingReplaceRequest() {
        }
        
        public FeedingReplaceRequest(Test.AsrsWebSvr.FeedingReplaceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Thok.WMS.Interface/")]
    public partial class FeedingReplaceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string BillNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Transer;
        
        public FeedingReplaceRequestBody() {
        }
        
        public FeedingReplaceRequestBody(string BillNo, string Transer) {
            this.BillNo = BillNo;
            this.Transer = Transer;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FeedingReplaceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FeedingReplaceResponse", Namespace="http://Thok.WMS.Interface/", Order=0)]
        public Test.AsrsWebSvr.FeedingReplaceResponseBody Body;
        
        public FeedingReplaceResponse() {
        }
        
        public FeedingReplaceResponse(Test.AsrsWebSvr.FeedingReplaceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Thok.WMS.Interface/")]
    public partial class FeedingReplaceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string FeedingReplaceResult;
        
        public FeedingReplaceResponseBody() {
        }
        
        public FeedingReplaceResponseBody(string FeedingReplaceResult) {
            this.FeedingReplaceResult = FeedingReplaceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OutStockbillreplaceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OutStockbillreplace", Namespace="http://Thok.WMS.Interface/", Order=0)]
        public Test.AsrsWebSvr.OutStockbillreplaceRequestBody Body;
        
        public OutStockbillreplaceRequest() {
        }
        
        public OutStockbillreplaceRequest(Test.AsrsWebSvr.OutStockbillreplaceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Thok.WMS.Interface/")]
    public partial class OutStockbillreplaceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string channel_no;
        
        public OutStockbillreplaceRequestBody() {
        }
        
        public OutStockbillreplaceRequestBody(string channel_no) {
            this.channel_no = channel_no;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OutStockbillreplaceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OutStockbillreplaceResponse", Namespace="http://Thok.WMS.Interface/", Order=0)]
        public Test.AsrsWebSvr.OutStockbillreplaceResponseBody Body;
        
        public OutStockbillreplaceResponse() {
        }
        
        public OutStockbillreplaceResponse(Test.AsrsWebSvr.OutStockbillreplaceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Thok.WMS.Interface/")]
    public partial class OutStockbillreplaceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string OutStockbillreplaceResult;
        
        public OutStockbillreplaceResponseBody() {
        }
        
        public OutStockbillreplaceResponseBody(string OutStockbillreplaceResult) {
            this.OutStockbillreplaceResult = OutStockbillreplaceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OutStockbilcanceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OutStockbilcance", Namespace="http://Thok.WMS.Interface/", Order=0)]
        public Test.AsrsWebSvr.OutStockbilcanceRequestBody Body;
        
        public OutStockbilcanceRequest() {
        }
        
        public OutStockbilcanceRequest(Test.AsrsWebSvr.OutStockbilcanceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Thok.WMS.Interface/")]
    public partial class OutStockbilcanceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string BillNo;
        
        public OutStockbilcanceRequestBody() {
        }
        
        public OutStockbilcanceRequestBody(string BillNo) {
            this.BillNo = BillNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OutStockbilcanceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OutStockbilcanceResponse", Namespace="http://Thok.WMS.Interface/", Order=0)]
        public Test.AsrsWebSvr.OutStockbilcanceResponseBody Body;
        
        public OutStockbilcanceResponse() {
        }
        
        public OutStockbilcanceResponse(Test.AsrsWebSvr.OutStockbilcanceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Thok.WMS.Interface/")]
    public partial class OutStockbilcanceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string OutStockbilcanceResult;
        
        public OutStockbilcanceResponseBody() {
        }
        
        public OutStockbilcanceResponseBody(string OutStockbilcanceResult) {
            this.OutStockbilcanceResult = OutStockbilcanceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OpenCollectionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OpenCollection", Namespace="http://Thok.WMS.Interface/", Order=0)]
        public Test.AsrsWebSvr.OpenCollectionRequestBody Body;
        
        public OpenCollectionRequest() {
        }
        
        public OpenCollectionRequest(Test.AsrsWebSvr.OpenCollectionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Thok.WMS.Interface/")]
    public partial class OpenCollectionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string BillNo;
        
        public OpenCollectionRequestBody() {
        }
        
        public OpenCollectionRequestBody(string BillNo) {
            this.BillNo = BillNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OpenCollectionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OpenCollectionResponse", Namespace="http://Thok.WMS.Interface/", Order=0)]
        public Test.AsrsWebSvr.OpenCollectionResponseBody Body;
        
        public OpenCollectionResponse() {
        }
        
        public OpenCollectionResponse(Test.AsrsWebSvr.OpenCollectionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Thok.WMS.Interface/")]
    public partial class OpenCollectionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string OpenCollectionResult;
        
        public OpenCollectionResponseBody() {
        }
        
        public OpenCollectionResponseBody(string OpenCollectionResult) {
            this.OpenCollectionResult = OpenCollectionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OpenBeginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OpenBegin", Namespace="http://Thok.WMS.Interface/", Order=0)]
        public Test.AsrsWebSvr.OpenBeginRequestBody Body;
        
        public OpenBeginRequest() {
        }
        
        public OpenBeginRequest(Test.AsrsWebSvr.OpenBeginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Thok.WMS.Interface/")]
    public partial class OpenBeginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string BillNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string State;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Startime;
        
        public OpenBeginRequestBody() {
        }
        
        public OpenBeginRequestBody(string BillNo, string State, string Startime) {
            this.BillNo = BillNo;
            this.State = State;
            this.Startime = Startime;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OpenBeginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OpenBeginResponse", Namespace="http://Thok.WMS.Interface/", Order=0)]
        public Test.AsrsWebSvr.OpenBeginResponseBody Body;
        
        public OpenBeginResponse() {
        }
        
        public OpenBeginResponse(Test.AsrsWebSvr.OpenBeginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Thok.WMS.Interface/")]
    public partial class OpenBeginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string OpenBeginResult;
        
        public OpenBeginResponseBody() {
        }
        
        public OpenBeginResponseBody(string OpenBeginResult) {
            this.OpenBeginResult = OpenBeginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OpenEndRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OpenEnd", Namespace="http://Thok.WMS.Interface/", Order=0)]
        public Test.AsrsWebSvr.OpenEndRequestBody Body;
        
        public OpenEndRequest() {
        }
        
        public OpenEndRequest(Test.AsrsWebSvr.OpenEndRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Thok.WMS.Interface/")]
    public partial class OpenEndRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string BillNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string State;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Endtime;
        
        public OpenEndRequestBody() {
        }
        
        public OpenEndRequestBody(string BillNo, string State, string Endtime) {
            this.BillNo = BillNo;
            this.State = State;
            this.Endtime = Endtime;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OpenEndResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OpenEndResponse", Namespace="http://Thok.WMS.Interface/", Order=0)]
        public Test.AsrsWebSvr.OpenEndResponseBody Body;
        
        public OpenEndResponse() {
        }
        
        public OpenEndResponse(Test.AsrsWebSvr.OpenEndResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Thok.WMS.Interface/")]
    public partial class OpenEndResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string OpenEndResult;
        
        public OpenEndResponseBody() {
        }
        
        public OpenEndResponseBody(string OpenEndResult) {
            this.OpenEndResult = OpenEndResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FeedingSendRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FeedingSend", Namespace="http://Thok.WMS.Interface/", Order=0)]
        public Test.AsrsWebSvr.FeedingSendRequestBody Body;
        
        public FeedingSendRequest() {
        }
        
        public FeedingSendRequest(Test.AsrsWebSvr.FeedingSendRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Thok.WMS.Interface/")]
    public partial class FeedingSendRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string BillNo;
        
        public FeedingSendRequestBody() {
        }
        
        public FeedingSendRequestBody(string BillNo) {
            this.BillNo = BillNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FeedingSendResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FeedingSendResponse", Namespace="http://Thok.WMS.Interface/", Order=0)]
        public Test.AsrsWebSvr.FeedingSendResponseBody Body;
        
        public FeedingSendResponse() {
        }
        
        public FeedingSendResponse(Test.AsrsWebSvr.FeedingSendResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Thok.WMS.Interface/")]
    public partial class FeedingSendResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string FeedingSendResult;
        
        public FeedingSendResponseBody() {
        }
        
        public FeedingSendResponseBody(string FeedingSendResult) {
            this.FeedingSendResult = FeedingSendResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AHZY_ESB_WMS_GETSSVSoapChannel : Test.AsrsWebSvr.AHZY_ESB_WMS_GETSSVSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AHZY_ESB_WMS_GETSSVSoapClient : System.ServiceModel.ClientBase<Test.AsrsWebSvr.AHZY_ESB_WMS_GETSSVSoap>, Test.AsrsWebSvr.AHZY_ESB_WMS_GETSSVSoap {
        
        public AHZY_ESB_WMS_GETSSVSoapClient() {
        }
        
        public AHZY_ESB_WMS_GETSSVSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AHZY_ESB_WMS_GETSSVSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AHZY_ESB_WMS_GETSSVSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AHZY_ESB_WMS_GETSSVSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Test.AsrsWebSvr.HelloWorldResponse Test.AsrsWebSvr.AHZY_ESB_WMS_GETSSVSoap.HelloWorld(Test.AsrsWebSvr.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld(string BillNo, string billtype, string finishdate) {
            Test.AsrsWebSvr.HelloWorldRequest inValue = new Test.AsrsWebSvr.HelloWorldRequest();
            inValue.Body = new Test.AsrsWebSvr.HelloWorldRequestBody();
            inValue.Body.BillNo = BillNo;
            inValue.Body.billtype = billtype;
            inValue.Body.finishdate = finishdate;
            Test.AsrsWebSvr.HelloWorldResponse retVal = ((Test.AsrsWebSvr.AHZY_ESB_WMS_GETSSVSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Test.AsrsWebSvr.StockinFinishResponse Test.AsrsWebSvr.AHZY_ESB_WMS_GETSSVSoap.StockinFinish(Test.AsrsWebSvr.StockinFinishRequest request) {
            return base.Channel.StockinFinish(request);
        }
        
        public string StockinFinish(string BillNo, string billtype, string finishdate) {
            Test.AsrsWebSvr.StockinFinishRequest inValue = new Test.AsrsWebSvr.StockinFinishRequest();
            inValue.Body = new Test.AsrsWebSvr.StockinFinishRequestBody();
            inValue.Body.BillNo = BillNo;
            inValue.Body.billtype = billtype;
            inValue.Body.finishdate = finishdate;
            Test.AsrsWebSvr.StockinFinishResponse retVal = ((Test.AsrsWebSvr.AHZY_ESB_WMS_GETSSVSoap)(this)).StockinFinish(inValue);
            return retVal.Body.StockinFinishResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Test.AsrsWebSvr.StockbackFinishResponse Test.AsrsWebSvr.AHZY_ESB_WMS_GETSSVSoap.StockbackFinish(Test.AsrsWebSvr.StockbackFinishRequest request) {
            return base.Channel.StockbackFinish(request);
        }
        
        public string StockbackFinish(string BillNo, string billtype, string finishdate) {
            Test.AsrsWebSvr.StockbackFinishRequest inValue = new Test.AsrsWebSvr.StockbackFinishRequest();
            inValue.Body = new Test.AsrsWebSvr.StockbackFinishRequestBody();
            inValue.Body.BillNo = BillNo;
            inValue.Body.billtype = billtype;
            inValue.Body.finishdate = finishdate;
            Test.AsrsWebSvr.StockbackFinishResponse retVal = ((Test.AsrsWebSvr.AHZY_ESB_WMS_GETSSVSoap)(this)).StockbackFinish(inValue);
            return retVal.Body.StockbackFinishResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Test.AsrsWebSvr.FeedFinishResponse Test.AsrsWebSvr.AHZY_ESB_WMS_GETSSVSoap.FeedFinish(Test.AsrsWebSvr.FeedFinishRequest request) {
            return base.Channel.FeedFinish(request);
        }
        
        public string FeedFinish(string BillNo, string billtype, string finishdate) {
            Test.AsrsWebSvr.FeedFinishRequest inValue = new Test.AsrsWebSvr.FeedFinishRequest();
            inValue.Body = new Test.AsrsWebSvr.FeedFinishRequestBody();
            inValue.Body.BillNo = BillNo;
            inValue.Body.billtype = billtype;
            inValue.Body.finishdate = finishdate;
            Test.AsrsWebSvr.FeedFinishResponse retVal = ((Test.AsrsWebSvr.AHZY_ESB_WMS_GETSSVSoap)(this)).FeedFinish(inValue);
            return retVal.Body.FeedFinishResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Test.AsrsWebSvr.StockOutBeginResponse Test.AsrsWebSvr.AHZY_ESB_WMS_GETSSVSoap.StockOutBegin(Test.AsrsWebSvr.StockOutBeginRequest request) {
            return base.Channel.StockOutBegin(request);
        }
        
        public string StockOutBegin(string BillNo, string State, string Startime) {
            Test.AsrsWebSvr.StockOutBeginRequest inValue = new Test.AsrsWebSvr.StockOutBeginRequest();
            inValue.Body = new Test.AsrsWebSvr.StockOutBeginRequestBody();
            inValue.Body.BillNo = BillNo;
            inValue.Body.State = State;
            inValue.Body.Startime = Startime;
            Test.AsrsWebSvr.StockOutBeginResponse retVal = ((Test.AsrsWebSvr.AHZY_ESB_WMS_GETSSVSoap)(this)).StockOutBegin(inValue);
            return retVal.Body.StockOutBeginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Test.AsrsWebSvr.StockOutEndResponse Test.AsrsWebSvr.AHZY_ESB_WMS_GETSSVSoap.StockOutEnd(Test.AsrsWebSvr.StockOutEndRequest request) {
            return base.Channel.StockOutEnd(request);
        }
        
        public string StockOutEnd(string BillNo, string State, string Endtime) {
            Test.AsrsWebSvr.StockOutEndRequest inValue = new Test.AsrsWebSvr.StockOutEndRequest();
            inValue.Body = new Test.AsrsWebSvr.StockOutEndRequestBody();
            inValue.Body.BillNo = BillNo;
            inValue.Body.State = State;
            inValue.Body.Endtime = Endtime;
            Test.AsrsWebSvr.StockOutEndResponse retVal = ((Test.AsrsWebSvr.AHZY_ESB_WMS_GETSSVSoap)(this)).StockOutEnd(inValue);
            return retVal.Body.StockOutEndResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Test.AsrsWebSvr.StockOutCollectionResponse Test.AsrsWebSvr.AHZY_ESB_WMS_GETSSVSoap.StockOutCollection(Test.AsrsWebSvr.StockOutCollectionRequest request) {
            return base.Channel.StockOutCollection(request);
        }
        
        public string StockOutCollection(string BillNo) {
            Test.AsrsWebSvr.StockOutCollectionRequest inValue = new Test.AsrsWebSvr.StockOutCollectionRequest();
            inValue.Body = new Test.AsrsWebSvr.StockOutCollectionRequestBody();
            inValue.Body.BillNo = BillNo;
            Test.AsrsWebSvr.StockOutCollectionResponse retVal = ((Test.AsrsWebSvr.AHZY_ESB_WMS_GETSSVSoap)(this)).StockOutCollection(inValue);
            return retVal.Body.StockOutCollectionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Test.AsrsWebSvr.FeedingReplaceResponse Test.AsrsWebSvr.AHZY_ESB_WMS_GETSSVSoap.FeedingReplace(Test.AsrsWebSvr.FeedingReplaceRequest request) {
            return base.Channel.FeedingReplace(request);
        }
        
        public string FeedingReplace(string BillNo, string Transer) {
            Test.AsrsWebSvr.FeedingReplaceRequest inValue = new Test.AsrsWebSvr.FeedingReplaceRequest();
            inValue.Body = new Test.AsrsWebSvr.FeedingReplaceRequestBody();
            inValue.Body.BillNo = BillNo;
            inValue.Body.Transer = Transer;
            Test.AsrsWebSvr.FeedingReplaceResponse retVal = ((Test.AsrsWebSvr.AHZY_ESB_WMS_GETSSVSoap)(this)).FeedingReplace(inValue);
            return retVal.Body.FeedingReplaceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Test.AsrsWebSvr.OutStockbillreplaceResponse Test.AsrsWebSvr.AHZY_ESB_WMS_GETSSVSoap.OutStockbillreplace(Test.AsrsWebSvr.OutStockbillreplaceRequest request) {
            return base.Channel.OutStockbillreplace(request);
        }
        
        public string OutStockbillreplace(string channel_no) {
            Test.AsrsWebSvr.OutStockbillreplaceRequest inValue = new Test.AsrsWebSvr.OutStockbillreplaceRequest();
            inValue.Body = new Test.AsrsWebSvr.OutStockbillreplaceRequestBody();
            inValue.Body.channel_no = channel_no;
            Test.AsrsWebSvr.OutStockbillreplaceResponse retVal = ((Test.AsrsWebSvr.AHZY_ESB_WMS_GETSSVSoap)(this)).OutStockbillreplace(inValue);
            return retVal.Body.OutStockbillreplaceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Test.AsrsWebSvr.OutStockbilcanceResponse Test.AsrsWebSvr.AHZY_ESB_WMS_GETSSVSoap.OutStockbilcance(Test.AsrsWebSvr.OutStockbilcanceRequest request) {
            return base.Channel.OutStockbilcance(request);
        }
        
        public string OutStockbilcance(string BillNo) {
            Test.AsrsWebSvr.OutStockbilcanceRequest inValue = new Test.AsrsWebSvr.OutStockbilcanceRequest();
            inValue.Body = new Test.AsrsWebSvr.OutStockbilcanceRequestBody();
            inValue.Body.BillNo = BillNo;
            Test.AsrsWebSvr.OutStockbilcanceResponse retVal = ((Test.AsrsWebSvr.AHZY_ESB_WMS_GETSSVSoap)(this)).OutStockbilcance(inValue);
            return retVal.Body.OutStockbilcanceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Test.AsrsWebSvr.OpenCollectionResponse Test.AsrsWebSvr.AHZY_ESB_WMS_GETSSVSoap.OpenCollection(Test.AsrsWebSvr.OpenCollectionRequest request) {
            return base.Channel.OpenCollection(request);
        }
        
        public string OpenCollection(string BillNo) {
            Test.AsrsWebSvr.OpenCollectionRequest inValue = new Test.AsrsWebSvr.OpenCollectionRequest();
            inValue.Body = new Test.AsrsWebSvr.OpenCollectionRequestBody();
            inValue.Body.BillNo = BillNo;
            Test.AsrsWebSvr.OpenCollectionResponse retVal = ((Test.AsrsWebSvr.AHZY_ESB_WMS_GETSSVSoap)(this)).OpenCollection(inValue);
            return retVal.Body.OpenCollectionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Test.AsrsWebSvr.OpenBeginResponse Test.AsrsWebSvr.AHZY_ESB_WMS_GETSSVSoap.OpenBegin(Test.AsrsWebSvr.OpenBeginRequest request) {
            return base.Channel.OpenBegin(request);
        }
        
        public string OpenBegin(string BillNo, string State, string Startime) {
            Test.AsrsWebSvr.OpenBeginRequest inValue = new Test.AsrsWebSvr.OpenBeginRequest();
            inValue.Body = new Test.AsrsWebSvr.OpenBeginRequestBody();
            inValue.Body.BillNo = BillNo;
            inValue.Body.State = State;
            inValue.Body.Startime = Startime;
            Test.AsrsWebSvr.OpenBeginResponse retVal = ((Test.AsrsWebSvr.AHZY_ESB_WMS_GETSSVSoap)(this)).OpenBegin(inValue);
            return retVal.Body.OpenBeginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Test.AsrsWebSvr.OpenEndResponse Test.AsrsWebSvr.AHZY_ESB_WMS_GETSSVSoap.OpenEnd(Test.AsrsWebSvr.OpenEndRequest request) {
            return base.Channel.OpenEnd(request);
        }
        
        public string OpenEnd(string BillNo, string State, string Endtime) {
            Test.AsrsWebSvr.OpenEndRequest inValue = new Test.AsrsWebSvr.OpenEndRequest();
            inValue.Body = new Test.AsrsWebSvr.OpenEndRequestBody();
            inValue.Body.BillNo = BillNo;
            inValue.Body.State = State;
            inValue.Body.Endtime = Endtime;
            Test.AsrsWebSvr.OpenEndResponse retVal = ((Test.AsrsWebSvr.AHZY_ESB_WMS_GETSSVSoap)(this)).OpenEnd(inValue);
            return retVal.Body.OpenEndResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Test.AsrsWebSvr.FeedingSendResponse Test.AsrsWebSvr.AHZY_ESB_WMS_GETSSVSoap.FeedingSend(Test.AsrsWebSvr.FeedingSendRequest request) {
            return base.Channel.FeedingSend(request);
        }
        
        public string FeedingSend(string BillNo) {
            Test.AsrsWebSvr.FeedingSendRequest inValue = new Test.AsrsWebSvr.FeedingSendRequest();
            inValue.Body = new Test.AsrsWebSvr.FeedingSendRequestBody();
            inValue.Body.BillNo = BillNo;
            Test.AsrsWebSvr.FeedingSendResponse retVal = ((Test.AsrsWebSvr.AHZY_ESB_WMS_GETSSVSoap)(this)).FeedingSend(inValue);
            return retVal.Body.FeedingSendResult;
        }
    }
}
