//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.225.
// 
#pragma warning disable 1591

namespace WMSWEBSERVICE.MESWs {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="MesYllkWsSoap", Namespace="http://Icss.Mes.DI/")]
    public partial class MesYllkWs : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback PFK_YLBLTL_BLRKWCOperationCompleted;
        
        private System.Threading.SendOrPostCallback PFK_YLBLTL_TLCKWCOperationCompleted;
        
        private System.Threading.SendOrPostCallback PFK_YLBL_BLTHSQOperationCompleted;
        
        private System.Threading.SendOrPostCallback PFK_YLBL_BLRKOperationCompleted;
        
        private System.Threading.SendOrPostCallback PFK_YLTC_GDKSOperationCompleted;
        
        private System.Threading.SendOrPostCallback PFK_YLTC_GDJSOperationCompleted;
        
        private System.Threading.SendOrPostCallback PFK_YLTC_GDGJOperationCompleted;
        
        private System.Threading.SendOrPostCallback PFK_KCGX_PFKCOperationCompleted;
        
        private System.Threading.SendOrPostCallback PFK_KCGX_KGXXOperationCompleted;
        
        private System.Threading.SendOrPostCallback PFK_YLTC_TLKSOperationCompleted;
        
        private System.Threading.SendOrPostCallback PFK_YLTC_TLJSOperationCompleted;
        
        private System.Threading.SendOrPostCallback PFK_YLTC_GDQXOperationCompleted;
        
        private System.Threading.SendOrPostCallback PFK_YLTC_GDKBTLGJOperationCompleted;
        
        private System.Threading.SendOrPostCallback PFK_YLTC_GDSQOperationCompleted;
        
        private System.Threading.SendOrPostCallback PFK_KCGX_YYTHOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public MesYllkWs() {
            this.Url = global::WMSWEBSERVICE.Properties.Settings.Default.WMSWEBSERVICE_MESWs_MesYllkWs;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event PFK_YLBLTL_BLRKWCCompletedEventHandler PFK_YLBLTL_BLRKWCCompleted;
        
        /// <remarks/>
        public event PFK_YLBLTL_TLCKWCCompletedEventHandler PFK_YLBLTL_TLCKWCCompleted;
        
        /// <remarks/>
        public event PFK_YLBL_BLTHSQCompletedEventHandler PFK_YLBL_BLTHSQCompleted;
        
        /// <remarks/>
        public event PFK_YLBL_BLRKCompletedEventHandler PFK_YLBL_BLRKCompleted;
        
        /// <remarks/>
        public event PFK_YLTC_GDKSCompletedEventHandler PFK_YLTC_GDKSCompleted;
        
        /// <remarks/>
        public event PFK_YLTC_GDJSCompletedEventHandler PFK_YLTC_GDJSCompleted;
        
        /// <remarks/>
        public event PFK_YLTC_GDGJCompletedEventHandler PFK_YLTC_GDGJCompleted;
        
        /// <remarks/>
        public event PFK_KCGX_PFKCCompletedEventHandler PFK_KCGX_PFKCCompleted;
        
        /// <remarks/>
        public event PFK_KCGX_KGXXCompletedEventHandler PFK_KCGX_KGXXCompleted;
        
        /// <remarks/>
        public event PFK_YLTC_TLKSCompletedEventHandler PFK_YLTC_TLKSCompleted;
        
        /// <remarks/>
        public event PFK_YLTC_TLJSCompletedEventHandler PFK_YLTC_TLJSCompleted;
        
        /// <remarks/>
        public event PFK_YLTC_GDQXCompletedEventHandler PFK_YLTC_GDQXCompleted;
        
        /// <remarks/>
        public event PFK_YLTC_GDKBTLGJCompletedEventHandler PFK_YLTC_GDKBTLGJCompleted;
        
        /// <remarks/>
        public event PFK_YLTC_GDSQCompletedEventHandler PFK_YLTC_GDSQCompleted;
        
        /// <remarks/>
        public event PFK_KCGX_YYTHCompletedEventHandler PFK_KCGX_YYTHCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Icss.Mes.DI/PFK_YLBLTL_BLRKWC", RequestNamespace="http://Icss.Mes.DI/", ResponseNamespace="http://Icss.Mes.DI/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string PFK_YLBLTL_BLRKWC(string xmlMessage) {
            object[] results = this.Invoke("PFK_YLBLTL_BLRKWC", new object[] {
                        xmlMessage});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void PFK_YLBLTL_BLRKWCAsync(string xmlMessage) {
            this.PFK_YLBLTL_BLRKWCAsync(xmlMessage, null);
        }
        
        /// <remarks/>
        public void PFK_YLBLTL_BLRKWCAsync(string xmlMessage, object userState) {
            if ((this.PFK_YLBLTL_BLRKWCOperationCompleted == null)) {
                this.PFK_YLBLTL_BLRKWCOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPFK_YLBLTL_BLRKWCOperationCompleted);
            }
            this.InvokeAsync("PFK_YLBLTL_BLRKWC", new object[] {
                        xmlMessage}, this.PFK_YLBLTL_BLRKWCOperationCompleted, userState);
        }
        
        private void OnPFK_YLBLTL_BLRKWCOperationCompleted(object arg) {
            if ((this.PFK_YLBLTL_BLRKWCCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PFK_YLBLTL_BLRKWCCompleted(this, new PFK_YLBLTL_BLRKWCCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Icss.Mes.DI/PFK_YLBLTL_TLCKWC", RequestNamespace="http://Icss.Mes.DI/", ResponseNamespace="http://Icss.Mes.DI/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string PFK_YLBLTL_TLCKWC(string xmlMessage) {
            object[] results = this.Invoke("PFK_YLBLTL_TLCKWC", new object[] {
                        xmlMessage});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void PFK_YLBLTL_TLCKWCAsync(string xmlMessage) {
            this.PFK_YLBLTL_TLCKWCAsync(xmlMessage, null);
        }
        
        /// <remarks/>
        public void PFK_YLBLTL_TLCKWCAsync(string xmlMessage, object userState) {
            if ((this.PFK_YLBLTL_TLCKWCOperationCompleted == null)) {
                this.PFK_YLBLTL_TLCKWCOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPFK_YLBLTL_TLCKWCOperationCompleted);
            }
            this.InvokeAsync("PFK_YLBLTL_TLCKWC", new object[] {
                        xmlMessage}, this.PFK_YLBLTL_TLCKWCOperationCompleted, userState);
        }
        
        private void OnPFK_YLBLTL_TLCKWCOperationCompleted(object arg) {
            if ((this.PFK_YLBLTL_TLCKWCCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PFK_YLBLTL_TLCKWCCompleted(this, new PFK_YLBLTL_TLCKWCCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Icss.Mes.DI/PFK_YLBL_BLTHSQ", RequestNamespace="http://Icss.Mes.DI/", ResponseNamespace="http://Icss.Mes.DI/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string PFK_YLBL_BLTHSQ(string xmlMessage) {
            object[] results = this.Invoke("PFK_YLBL_BLTHSQ", new object[] {
                        xmlMessage});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void PFK_YLBL_BLTHSQAsync(string xmlMessage) {
            this.PFK_YLBL_BLTHSQAsync(xmlMessage, null);
        }
        
        /// <remarks/>
        public void PFK_YLBL_BLTHSQAsync(string xmlMessage, object userState) {
            if ((this.PFK_YLBL_BLTHSQOperationCompleted == null)) {
                this.PFK_YLBL_BLTHSQOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPFK_YLBL_BLTHSQOperationCompleted);
            }
            this.InvokeAsync("PFK_YLBL_BLTHSQ", new object[] {
                        xmlMessage}, this.PFK_YLBL_BLTHSQOperationCompleted, userState);
        }
        
        private void OnPFK_YLBL_BLTHSQOperationCompleted(object arg) {
            if ((this.PFK_YLBL_BLTHSQCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PFK_YLBL_BLTHSQCompleted(this, new PFK_YLBL_BLTHSQCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Icss.Mes.DI/PFK_YLBL_BLRK", RequestNamespace="http://Icss.Mes.DI/", ResponseNamespace="http://Icss.Mes.DI/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string PFK_YLBL_BLRK(string xmlMessage) {
            object[] results = this.Invoke("PFK_YLBL_BLRK", new object[] {
                        xmlMessage});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void PFK_YLBL_BLRKAsync(string xmlMessage) {
            this.PFK_YLBL_BLRKAsync(xmlMessage, null);
        }
        
        /// <remarks/>
        public void PFK_YLBL_BLRKAsync(string xmlMessage, object userState) {
            if ((this.PFK_YLBL_BLRKOperationCompleted == null)) {
                this.PFK_YLBL_BLRKOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPFK_YLBL_BLRKOperationCompleted);
            }
            this.InvokeAsync("PFK_YLBL_BLRK", new object[] {
                        xmlMessage}, this.PFK_YLBL_BLRKOperationCompleted, userState);
        }
        
        private void OnPFK_YLBL_BLRKOperationCompleted(object arg) {
            if ((this.PFK_YLBL_BLRKCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PFK_YLBL_BLRKCompleted(this, new PFK_YLBL_BLRKCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Icss.Mes.DI/PFK_YLTC_GDKS", RequestNamespace="http://Icss.Mes.DI/", ResponseNamespace="http://Icss.Mes.DI/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string PFK_YLTC_GDKS(string xmlMessage) {
            object[] results = this.Invoke("PFK_YLTC_GDKS", new object[] {
                        xmlMessage});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void PFK_YLTC_GDKSAsync(string xmlMessage) {
            this.PFK_YLTC_GDKSAsync(xmlMessage, null);
        }
        
        /// <remarks/>
        public void PFK_YLTC_GDKSAsync(string xmlMessage, object userState) {
            if ((this.PFK_YLTC_GDKSOperationCompleted == null)) {
                this.PFK_YLTC_GDKSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPFK_YLTC_GDKSOperationCompleted);
            }
            this.InvokeAsync("PFK_YLTC_GDKS", new object[] {
                        xmlMessage}, this.PFK_YLTC_GDKSOperationCompleted, userState);
        }
        
        private void OnPFK_YLTC_GDKSOperationCompleted(object arg) {
            if ((this.PFK_YLTC_GDKSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PFK_YLTC_GDKSCompleted(this, new PFK_YLTC_GDKSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Icss.Mes.DI/PFK_YLTC_GDJS", RequestNamespace="http://Icss.Mes.DI/", ResponseNamespace="http://Icss.Mes.DI/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string PFK_YLTC_GDJS(string xmlMessage) {
            object[] results = this.Invoke("PFK_YLTC_GDJS", new object[] {
                        xmlMessage});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void PFK_YLTC_GDJSAsync(string xmlMessage) {
            this.PFK_YLTC_GDJSAsync(xmlMessage, null);
        }
        
        /// <remarks/>
        public void PFK_YLTC_GDJSAsync(string xmlMessage, object userState) {
            if ((this.PFK_YLTC_GDJSOperationCompleted == null)) {
                this.PFK_YLTC_GDJSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPFK_YLTC_GDJSOperationCompleted);
            }
            this.InvokeAsync("PFK_YLTC_GDJS", new object[] {
                        xmlMessage}, this.PFK_YLTC_GDJSOperationCompleted, userState);
        }
        
        private void OnPFK_YLTC_GDJSOperationCompleted(object arg) {
            if ((this.PFK_YLTC_GDJSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PFK_YLTC_GDJSCompleted(this, new PFK_YLTC_GDJSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Icss.Mes.DI/PFK_YLTC_GDGJ", RequestNamespace="http://Icss.Mes.DI/", ResponseNamespace="http://Icss.Mes.DI/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string PFK_YLTC_GDGJ(string xmlMessage) {
            object[] results = this.Invoke("PFK_YLTC_GDGJ", new object[] {
                        xmlMessage});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void PFK_YLTC_GDGJAsync(string xmlMessage) {
            this.PFK_YLTC_GDGJAsync(xmlMessage, null);
        }
        
        /// <remarks/>
        public void PFK_YLTC_GDGJAsync(string xmlMessage, object userState) {
            if ((this.PFK_YLTC_GDGJOperationCompleted == null)) {
                this.PFK_YLTC_GDGJOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPFK_YLTC_GDGJOperationCompleted);
            }
            this.InvokeAsync("PFK_YLTC_GDGJ", new object[] {
                        xmlMessage}, this.PFK_YLTC_GDGJOperationCompleted, userState);
        }
        
        private void OnPFK_YLTC_GDGJOperationCompleted(object arg) {
            if ((this.PFK_YLTC_GDGJCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PFK_YLTC_GDGJCompleted(this, new PFK_YLTC_GDGJCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Icss.Mes.DI/PFK_KCGX_PFKC", RequestNamespace="http://Icss.Mes.DI/", ResponseNamespace="http://Icss.Mes.DI/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string PFK_KCGX_PFKC(string xmlMessage) {
            object[] results = this.Invoke("PFK_KCGX_PFKC", new object[] {
                        xmlMessage});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void PFK_KCGX_PFKCAsync(string xmlMessage) {
            this.PFK_KCGX_PFKCAsync(xmlMessage, null);
        }
        
        /// <remarks/>
        public void PFK_KCGX_PFKCAsync(string xmlMessage, object userState) {
            if ((this.PFK_KCGX_PFKCOperationCompleted == null)) {
                this.PFK_KCGX_PFKCOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPFK_KCGX_PFKCOperationCompleted);
            }
            this.InvokeAsync("PFK_KCGX_PFKC", new object[] {
                        xmlMessage}, this.PFK_KCGX_PFKCOperationCompleted, userState);
        }
        
        private void OnPFK_KCGX_PFKCOperationCompleted(object arg) {
            if ((this.PFK_KCGX_PFKCCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PFK_KCGX_PFKCCompleted(this, new PFK_KCGX_PFKCCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Icss.Mes.DI/PFK_KCGX_KGXX", RequestNamespace="http://Icss.Mes.DI/", ResponseNamespace="http://Icss.Mes.DI/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string PFK_KCGX_KGXX(string xmlMessage) {
            object[] results = this.Invoke("PFK_KCGX_KGXX", new object[] {
                        xmlMessage});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void PFK_KCGX_KGXXAsync(string xmlMessage) {
            this.PFK_KCGX_KGXXAsync(xmlMessage, null);
        }
        
        /// <remarks/>
        public void PFK_KCGX_KGXXAsync(string xmlMessage, object userState) {
            if ((this.PFK_KCGX_KGXXOperationCompleted == null)) {
                this.PFK_KCGX_KGXXOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPFK_KCGX_KGXXOperationCompleted);
            }
            this.InvokeAsync("PFK_KCGX_KGXX", new object[] {
                        xmlMessage}, this.PFK_KCGX_KGXXOperationCompleted, userState);
        }
        
        private void OnPFK_KCGX_KGXXOperationCompleted(object arg) {
            if ((this.PFK_KCGX_KGXXCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PFK_KCGX_KGXXCompleted(this, new PFK_KCGX_KGXXCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Icss.Mes.DI/PFK_YLTC_TLKS", RequestNamespace="http://Icss.Mes.DI/", ResponseNamespace="http://Icss.Mes.DI/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string PFK_YLTC_TLKS(string xmlMessage) {
            object[] results = this.Invoke("PFK_YLTC_TLKS", new object[] {
                        xmlMessage});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void PFK_YLTC_TLKSAsync(string xmlMessage) {
            this.PFK_YLTC_TLKSAsync(xmlMessage, null);
        }
        
        /// <remarks/>
        public void PFK_YLTC_TLKSAsync(string xmlMessage, object userState) {
            if ((this.PFK_YLTC_TLKSOperationCompleted == null)) {
                this.PFK_YLTC_TLKSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPFK_YLTC_TLKSOperationCompleted);
            }
            this.InvokeAsync("PFK_YLTC_TLKS", new object[] {
                        xmlMessage}, this.PFK_YLTC_TLKSOperationCompleted, userState);
        }
        
        private void OnPFK_YLTC_TLKSOperationCompleted(object arg) {
            if ((this.PFK_YLTC_TLKSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PFK_YLTC_TLKSCompleted(this, new PFK_YLTC_TLKSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Icss.Mes.DI/PFK_YLTC_TLJS", RequestNamespace="http://Icss.Mes.DI/", ResponseNamespace="http://Icss.Mes.DI/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string PFK_YLTC_TLJS(string xmlMessage) {
            object[] results = this.Invoke("PFK_YLTC_TLJS", new object[] {
                        xmlMessage});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void PFK_YLTC_TLJSAsync(string xmlMessage) {
            this.PFK_YLTC_TLJSAsync(xmlMessage, null);
        }
        
        /// <remarks/>
        public void PFK_YLTC_TLJSAsync(string xmlMessage, object userState) {
            if ((this.PFK_YLTC_TLJSOperationCompleted == null)) {
                this.PFK_YLTC_TLJSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPFK_YLTC_TLJSOperationCompleted);
            }
            this.InvokeAsync("PFK_YLTC_TLJS", new object[] {
                        xmlMessage}, this.PFK_YLTC_TLJSOperationCompleted, userState);
        }
        
        private void OnPFK_YLTC_TLJSOperationCompleted(object arg) {
            if ((this.PFK_YLTC_TLJSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PFK_YLTC_TLJSCompleted(this, new PFK_YLTC_TLJSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Icss.Mes.DI/PFK_YLTC_GDQX", RequestNamespace="http://Icss.Mes.DI/", ResponseNamespace="http://Icss.Mes.DI/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string PFK_YLTC_GDQX(string xmlMessage) {
            object[] results = this.Invoke("PFK_YLTC_GDQX", new object[] {
                        xmlMessage});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void PFK_YLTC_GDQXAsync(string xmlMessage) {
            this.PFK_YLTC_GDQXAsync(xmlMessage, null);
        }
        
        /// <remarks/>
        public void PFK_YLTC_GDQXAsync(string xmlMessage, object userState) {
            if ((this.PFK_YLTC_GDQXOperationCompleted == null)) {
                this.PFK_YLTC_GDQXOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPFK_YLTC_GDQXOperationCompleted);
            }
            this.InvokeAsync("PFK_YLTC_GDQX", new object[] {
                        xmlMessage}, this.PFK_YLTC_GDQXOperationCompleted, userState);
        }
        
        private void OnPFK_YLTC_GDQXOperationCompleted(object arg) {
            if ((this.PFK_YLTC_GDQXCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PFK_YLTC_GDQXCompleted(this, new PFK_YLTC_GDQXCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Icss.Mes.DI/PFK_YLTC_GDKBTLGJ", RequestNamespace="http://Icss.Mes.DI/", ResponseNamespace="http://Icss.Mes.DI/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string PFK_YLTC_GDKBTLGJ(string xmlMessage) {
            object[] results = this.Invoke("PFK_YLTC_GDKBTLGJ", new object[] {
                        xmlMessage});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void PFK_YLTC_GDKBTLGJAsync(string xmlMessage) {
            this.PFK_YLTC_GDKBTLGJAsync(xmlMessage, null);
        }
        
        /// <remarks/>
        public void PFK_YLTC_GDKBTLGJAsync(string xmlMessage, object userState) {
            if ((this.PFK_YLTC_GDKBTLGJOperationCompleted == null)) {
                this.PFK_YLTC_GDKBTLGJOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPFK_YLTC_GDKBTLGJOperationCompleted);
            }
            this.InvokeAsync("PFK_YLTC_GDKBTLGJ", new object[] {
                        xmlMessage}, this.PFK_YLTC_GDKBTLGJOperationCompleted, userState);
        }
        
        private void OnPFK_YLTC_GDKBTLGJOperationCompleted(object arg) {
            if ((this.PFK_YLTC_GDKBTLGJCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PFK_YLTC_GDKBTLGJCompleted(this, new PFK_YLTC_GDKBTLGJCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Icss.Mes.DI/PFK_YLTC_GDSQ", RequestNamespace="http://Icss.Mes.DI/", ResponseNamespace="http://Icss.Mes.DI/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string PFK_YLTC_GDSQ(string xmlMessage) {
            object[] results = this.Invoke("PFK_YLTC_GDSQ", new object[] {
                        xmlMessage});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void PFK_YLTC_GDSQAsync(string xmlMessage) {
            this.PFK_YLTC_GDSQAsync(xmlMessage, null);
        }
        
        /// <remarks/>
        public void PFK_YLTC_GDSQAsync(string xmlMessage, object userState) {
            if ((this.PFK_YLTC_GDSQOperationCompleted == null)) {
                this.PFK_YLTC_GDSQOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPFK_YLTC_GDSQOperationCompleted);
            }
            this.InvokeAsync("PFK_YLTC_GDSQ", new object[] {
                        xmlMessage}, this.PFK_YLTC_GDSQOperationCompleted, userState);
        }
        
        private void OnPFK_YLTC_GDSQOperationCompleted(object arg) {
            if ((this.PFK_YLTC_GDSQCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PFK_YLTC_GDSQCompleted(this, new PFK_YLTC_GDSQCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Icss.Mes.DI/PFK_KCGX_YYTH", RequestNamespace="http://Icss.Mes.DI/", ResponseNamespace="http://Icss.Mes.DI/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string PFK_KCGX_YYTH(string xmlMessage) {
            object[] results = this.Invoke("PFK_KCGX_YYTH", new object[] {
                        xmlMessage});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void PFK_KCGX_YYTHAsync(string xmlMessage) {
            this.PFK_KCGX_YYTHAsync(xmlMessage, null);
        }
        
        /// <remarks/>
        public void PFK_KCGX_YYTHAsync(string xmlMessage, object userState) {
            if ((this.PFK_KCGX_YYTHOperationCompleted == null)) {
                this.PFK_KCGX_YYTHOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPFK_KCGX_YYTHOperationCompleted);
            }
            this.InvokeAsync("PFK_KCGX_YYTH", new object[] {
                        xmlMessage}, this.PFK_KCGX_YYTHOperationCompleted, userState);
        }
        
        private void OnPFK_KCGX_YYTHOperationCompleted(object arg) {
            if ((this.PFK_KCGX_YYTHCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PFK_KCGX_YYTHCompleted(this, new PFK_KCGX_YYTHCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void PFK_YLBLTL_BLRKWCCompletedEventHandler(object sender, PFK_YLBLTL_BLRKWCCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PFK_YLBLTL_BLRKWCCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PFK_YLBLTL_BLRKWCCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void PFK_YLBLTL_TLCKWCCompletedEventHandler(object sender, PFK_YLBLTL_TLCKWCCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PFK_YLBLTL_TLCKWCCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PFK_YLBLTL_TLCKWCCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void PFK_YLBL_BLTHSQCompletedEventHandler(object sender, PFK_YLBL_BLTHSQCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PFK_YLBL_BLTHSQCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PFK_YLBL_BLTHSQCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void PFK_YLBL_BLRKCompletedEventHandler(object sender, PFK_YLBL_BLRKCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PFK_YLBL_BLRKCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PFK_YLBL_BLRKCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void PFK_YLTC_GDKSCompletedEventHandler(object sender, PFK_YLTC_GDKSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PFK_YLTC_GDKSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PFK_YLTC_GDKSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void PFK_YLTC_GDJSCompletedEventHandler(object sender, PFK_YLTC_GDJSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PFK_YLTC_GDJSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PFK_YLTC_GDJSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void PFK_YLTC_GDGJCompletedEventHandler(object sender, PFK_YLTC_GDGJCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PFK_YLTC_GDGJCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PFK_YLTC_GDGJCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void PFK_KCGX_PFKCCompletedEventHandler(object sender, PFK_KCGX_PFKCCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PFK_KCGX_PFKCCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PFK_KCGX_PFKCCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void PFK_KCGX_KGXXCompletedEventHandler(object sender, PFK_KCGX_KGXXCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PFK_KCGX_KGXXCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PFK_KCGX_KGXXCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void PFK_YLTC_TLKSCompletedEventHandler(object sender, PFK_YLTC_TLKSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PFK_YLTC_TLKSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PFK_YLTC_TLKSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void PFK_YLTC_TLJSCompletedEventHandler(object sender, PFK_YLTC_TLJSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PFK_YLTC_TLJSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PFK_YLTC_TLJSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void PFK_YLTC_GDQXCompletedEventHandler(object sender, PFK_YLTC_GDQXCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PFK_YLTC_GDQXCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PFK_YLTC_GDQXCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void PFK_YLTC_GDKBTLGJCompletedEventHandler(object sender, PFK_YLTC_GDKBTLGJCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PFK_YLTC_GDKBTLGJCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PFK_YLTC_GDKBTLGJCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void PFK_YLTC_GDSQCompletedEventHandler(object sender, PFK_YLTC_GDSQCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PFK_YLTC_GDSQCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PFK_YLTC_GDSQCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void PFK_KCGX_YYTHCompletedEventHandler(object sender, PFK_KCGX_YYTHCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PFK_KCGX_YYTHCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PFK_KCGX_YYTHCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591