//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.WMSSV {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Thok.WMS.Interface/", ConfigurationName="WMSSV.AHZY_ESB_WMS_GETSSVSoap")]
    public interface AHZY_ESB_WMS_GETSSVSoap {
        
        // CODEGEN: Generating message contract since element name BillNo from namespace http://Thok.WMS.Interface/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Thok.WMS.Interface/HelloWorld", ReplyAction="*")]
        WMS.WMSSV.HelloWorldResponse HelloWorld(WMS.WMSSV.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name BillNo from namespace http://Thok.WMS.Interface/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Thok.WMS.Interface/StockinFinish", ReplyAction="*")]
        WMS.WMSSV.StockinFinishResponse StockinFinish(WMS.WMSSV.StockinFinishRequest request);
        
        // CODEGEN: Generating message contract since element name BillNo from namespace http://Thok.WMS.Interface/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Thok.WMS.Interface/StockbackFinish", ReplyAction="*")]
        WMS.WMSSV.StockbackFinishResponse StockbackFinish(WMS.WMSSV.StockbackFinishRequest request);
        
        // CODEGEN: Generating message contract since element name BillNo from namespace http://Thok.WMS.Interface/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Thok.WMS.Interface/FeedFinish", ReplyAction="*")]
        WMS.WMSSV.FeedFinishResponse FeedFinish(WMS.WMSSV.FeedFinishRequest request);
        
        // CODEGEN: Generating message contract since element name BillNo from namespace http://Thok.WMS.Interface/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Thok.WMS.Interface/StockOutBegin", ReplyAction="*")]
        WMS.WMSSV.StockOutBeginResponse StockOutBegin(WMS.WMSSV.StockOutBeginRequest request);
        
        // CODEGEN: Generating message contract since element name BillNo from namespace http://Thok.WMS.Interface/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Thok.WMS.Interface/StockOutEnd", ReplyAction="*")]
        WMS.WMSSV.StockOutEndResponse StockOutEnd(WMS.WMSSV.StockOutEndRequest request);
        
        // CODEGEN: Generating message contract since element name BillNo from namespace http://Thok.WMS.Interface/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Thok.WMS.Interface/StockOutCollection", ReplyAction="*")]
        WMS.WMSSV.StockOutCollectionResponse StockOutCollection(WMS.WMSSV.StockOutCollectionRequest request);
        
        // CODEGEN: Generating message contract since element name BillNo from namespace http://Thok.WMS.Interface/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Thok.WMS.Interface/FeedingReplace", ReplyAction="*")]
        WMS.WMSSV.FeedingReplaceResponse FeedingReplace(WMS.WMSSV.FeedingReplaceRequest request);
        
        // CODEGEN: Generating message contract since element name channel_no from namespace http://Thok.WMS.Interface/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Thok.WMS.Interface/OutStockbillreplace", ReplyAction="*")]
        WMS.WMSSV.OutStockbillreplaceResponse OutStockbillreplace(WMS.WMSSV.OutStockbillreplaceRequest request);
        
        // CODEGEN: Generating message contract since element name BillNo from namespace http://Thok.WMS.Interface/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Thok.WMS.Interface/OutStockbilcance", ReplyAction="*")]
        WMS.WMSSV.OutStockbilcanceResponse OutStockbilcance(WMS.WMSSV.OutStockbilcanceRequest request);
        
        // CODEGEN: Generating message contract since element name BillNo from namespace http://Thok.WMS.Interface/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Thok.WMS.Interface/OpenCollection", ReplyAction="*")]
        WMS.WMSSV.OpenCollectionResponse OpenCollection(WMS.WMSSV.OpenCollectionRequest request);
        
        // CODEGEN: Generating message contract since element name BillNo from namespace http://Thok.WMS.Interface/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Thok.WMS.Interface/OpenBegin", ReplyAction="*")]
        WMS.WMSSV.OpenBeginResponse OpenBegin(WMS.WMSSV.OpenBeginRequest request);
        
        // CODEGEN: Generating message contract since element name BillNo from namespace http://Thok.WMS.Interface/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Thok.WMS.Interface/OpenEnd", ReplyAction="*")]
        WMS.WMSSV.OpenEndResponse OpenEnd(WMS.WMSSV.OpenEndRequest request);
        
        // CODEGEN: Generating message contract since element name BillNo from namespace http://Thok.WMS.Interface/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Thok.WMS.Interface/FeedingSend", ReplyAction="*")]
        WMS.WMSSV.FeedingSendResponse FeedingSend(WMS.WMSSV.FeedingSendRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://Thok.WMS.Interface/", Order=0)]
        public WMS.WMSSV.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(WMS.WMSSV.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Thok.WMS.Interface/")]
    public partial class HelloWorldRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string BillNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string billtype;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string finishdate;
        
        public HelloWorldRequestBody() {
        }
        
        public HelloWorldRequestBody(string BillNo, string billtype, string finishdate) {
            this.BillNo = BillNo;
            this.billtype = billtype;
            this.finishdate = finishdate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://Thok.WMS.Interface/", Order=0)]
        public WMS.WMSSV.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(WMS.WMSSV.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Thok.WMS.Interface/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StockinFinishRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="StockinFinish", Namespace="http://Thok.WMS.Interface/", Order=0)]
        public WMS.WMSSV.StockinFinishRequestBody Body;
        
        public StockinFinishRequest() {
        }
        
        public StockinFinishRequest(WMS.WMSSV.StockinFinishRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Thok.WMS.Interface/")]
    public partial class StockinFinishRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string BillNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string billtype;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string finishdate;
        
        public StockinFinishRequestBody() {
        }
        
        public StockinFinishRequestBody(string BillNo, string billtype, string finishdate) {
            this.BillNo = BillNo;
            this.billtype = billtype;
            this.finishdate = finishdate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StockinFinishResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="StockinFinishResponse", Namespace="http://Thok.WMS.Interface/", Order=0)]
        public WMS.WMSSV.StockinFinishResponseBody Body;
        
        public StockinFinishResponse() {
        }
        
        public StockinFinishResponse(WMS.WMSSV.StockinFinishResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Thok.WMS.Interface/")]
    public partial class StockinFinishResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string StockinFinishResult;
        
        public StockinFinishResponseBody() {
        }
        
        public StockinFinishResponseBody(string StockinFinishResult) {
            this.StockinFinishResult = StockinFinishResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StockbackFinishRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="StockbackFinish", Namespace="http://Thok.WMS.Interface/", Order=0)]
        public WMS.WMSSV.StockbackFinishRequestBody Body;
        
        public StockbackFinishRequest() {
        }
        
        public StockbackFinishRequest(WMS.WMSSV.StockbackFinishRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Thok.WMS.Interface/")]
    public partial class StockbackFinishRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string BillNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string billtype;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string finishdate;
        
        public StockbackFinishRequestBody() {
        }
        
        public StockbackFinishRequestBody(string BillNo, string billtype, string finishdate) {
            this.BillNo = BillNo;
            this.billtype = billtype;
            this.finishdate = finishdate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StockbackFinishResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="StockbackFinishResponse", Namespace="http://Thok.WMS.Interface/", Order=0)]
        public WMS.WMSSV.StockbackFinishResponseBody Body;
        
        public StockbackFinishResponse() {
        }
        
        public StockbackFinishResponse(WMS.WMSSV.StockbackFinishResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Thok.WMS.Interface/")]
    public partial class StockbackFinishResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string StockbackFinishResult;
        
        public StockbackFinishResponseBody() {
        }
        
        public StockbackFinishResponseBody(string StockbackFinishResult) {
            this.StockbackFinishResult = StockbackFinishResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FeedFinishRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FeedFinish", Namespace="http://Thok.WMS.Interface/", Order=0)]
        public WMS.WMSSV.FeedFinishRequestBody Body;
        
        public FeedFinishRequest() {
        }
        
        public FeedFinishRequest(WMS.WMSSV.FeedFinishRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Thok.WMS.Interface/")]
    public partial class FeedFinishRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string BillNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string billtype;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string finishdate;
        
        public FeedFinishRequestBody() {
        }
        
        public FeedFinishRequestBody(string BillNo, string billtype, string finishdate) {
            this.BillNo = BillNo;
            this.billtype = billtype;
            this.finishdate = finishdate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FeedFinishResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FeedFinishResponse", Namespace="http://Thok.WMS.Interface/", Order=0)]
        public WMS.WMSSV.FeedFinishResponseBody Body;
        
        public FeedFinishResponse() {
        }
        
        public FeedFinishResponse(WMS.WMSSV.FeedFinishResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Thok.WMS.Interface/")]
    public partial class FeedFinishResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string FeedFinishResult;
        
        public FeedFinishResponseBody() {
        }
        
        public FeedFinishResponseBody(string FeedFinishResult) {
            this.FeedFinishResult = FeedFinishResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StockOutBeginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="StockOutBegin", Namespace="http://Thok.WMS.Interface/", Order=0)]
        public WMS.WMSSV.StockOutBeginRequestBody Body;
        
        public StockOutBeginRequest() {
        }
        
        public StockOutBeginRequest(WMS.WMSSV.StockOutBeginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Thok.WMS.Interface/")]
    public partial class StockOutBeginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string BillNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string State;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Startime;
        
        public StockOutBeginRequestBody() {
        }
        
        public StockOutBeginRequestBody(string BillNo, string State, string Startime) {
            this.BillNo = BillNo;
            this.State = State;
            this.Startime = Startime;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StockOutBeginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="StockOutBeginResponse", Namespace="http://Thok.WMS.Interface/", Order=0)]
        public WMS.WMSSV.StockOutBeginResponseBody Body;
        
        public StockOutBeginResponse() {
        }
        
        public StockOutBeginResponse(WMS.WMSSV.StockOutBeginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Thok.WMS.Interface/")]
    public partial class StockOutBeginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string StockOutBeginResult;
        
        public StockOutBeginResponseBody() {
        }
        
        public StockOutBeginResponseBody(string StockOutBeginResult) {
            this.StockOutBeginResult = StockOutBeginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StockOutEndRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="StockOutEnd", Namespace="http://Thok.WMS.Interface/", Order=0)]
        public WMS.WMSSV.StockOutEndRequestBody Body;
        
        public StockOutEndRequest() {
        }
        
        public StockOutEndRequest(WMS.WMSSV.StockOutEndRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Thok.WMS.Interface/")]
    public partial class StockOutEndRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string BillNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string State;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Endtime;
        
        public StockOutEndRequestBody() {
        }
        
        public StockOutEndRequestBody(string BillNo, string State, string Endtime) {
            this.BillNo = BillNo;
            this.State = State;
            this.Endtime = Endtime;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StockOutEndResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="StockOutEndResponse", Namespace="http://Thok.WMS.Interface/", Order=0)]
        public WMS.WMSSV.StockOutEndResponseBody Body;
        
        public StockOutEndResponse() {
        }
        
        public StockOutEndResponse(WMS.WMSSV.StockOutEndResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Thok.WMS.Interface/")]
    public partial class StockOutEndResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string StockOutEndResult;
        
        public StockOutEndResponseBody() {
        }
        
        public StockOutEndResponseBody(string StockOutEndResult) {
            this.StockOutEndResult = StockOutEndResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StockOutCollectionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="StockOutCollection", Namespace="http://Thok.WMS.Interface/", Order=0)]
        public WMS.WMSSV.StockOutCollectionRequestBody Body;
        
        public StockOutCollectionRequest() {
        }
        
        public StockOutCollectionRequest(WMS.WMSSV.StockOutCollectionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Thok.WMS.Interface/")]
    public partial class StockOutCollectionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string BillNo;
        
        public StockOutCollectionRequestBody() {
        }
        
        public StockOutCollectionRequestBody(string BillNo) {
            this.BillNo = BillNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StockOutCollectionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="StockOutCollectionResponse", Namespace="http://Thok.WMS.Interface/", Order=0)]
        public WMS.WMSSV.StockOutCollectionResponseBody Body;
        
        public StockOutCollectionResponse() {
        }
        
        public StockOutCollectionResponse(WMS.WMSSV.StockOutCollectionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Thok.WMS.Interface/")]
    public partial class StockOutCollectionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string StockOutCollectionResult;
        
        public StockOutCollectionResponseBody() {
        }
        
        public StockOutCollectionResponseBody(string StockOutCollectionResult) {
            this.StockOutCollectionResult = StockOutCollectionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FeedingReplaceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FeedingReplace", Namespace="http://Thok.WMS.Interface/", Order=0)]
        public WMS.WMSSV.FeedingReplaceRequestBody Body;
        
        public FeedingReplaceRequest() {
        }
        
        public FeedingReplaceRequest(WMS.WMSSV.FeedingReplaceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Thok.WMS.Interface/")]
    public partial class FeedingReplaceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string BillNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Transer;
        
        public FeedingReplaceRequestBody() {
        }
        
        public FeedingReplaceRequestBody(string BillNo, string Transer) {
            this.BillNo = BillNo;
            this.Transer = Transer;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FeedingReplaceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FeedingReplaceResponse", Namespace="http://Thok.WMS.Interface/", Order=0)]
        public WMS.WMSSV.FeedingReplaceResponseBody Body;
        
        public FeedingReplaceResponse() {
        }
        
        public FeedingReplaceResponse(WMS.WMSSV.FeedingReplaceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Thok.WMS.Interface/")]
    public partial class FeedingReplaceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string FeedingReplaceResult;
        
        public FeedingReplaceResponseBody() {
        }
        
        public FeedingReplaceResponseBody(string FeedingReplaceResult) {
            this.FeedingReplaceResult = FeedingReplaceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OutStockbillreplaceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OutStockbillreplace", Namespace="http://Thok.WMS.Interface/", Order=0)]
        public WMS.WMSSV.OutStockbillreplaceRequestBody Body;
        
        public OutStockbillreplaceRequest() {
        }
        
        public OutStockbillreplaceRequest(WMS.WMSSV.OutStockbillreplaceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Thok.WMS.Interface/")]
    public partial class OutStockbillreplaceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string channel_no;
        
        public OutStockbillreplaceRequestBody() {
        }
        
        public OutStockbillreplaceRequestBody(string channel_no) {
            this.channel_no = channel_no;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OutStockbillreplaceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OutStockbillreplaceResponse", Namespace="http://Thok.WMS.Interface/", Order=0)]
        public WMS.WMSSV.OutStockbillreplaceResponseBody Body;
        
        public OutStockbillreplaceResponse() {
        }
        
        public OutStockbillreplaceResponse(WMS.WMSSV.OutStockbillreplaceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Thok.WMS.Interface/")]
    public partial class OutStockbillreplaceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string OutStockbillreplaceResult;
        
        public OutStockbillreplaceResponseBody() {
        }
        
        public OutStockbillreplaceResponseBody(string OutStockbillreplaceResult) {
            this.OutStockbillreplaceResult = OutStockbillreplaceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OutStockbilcanceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OutStockbilcance", Namespace="http://Thok.WMS.Interface/", Order=0)]
        public WMS.WMSSV.OutStockbilcanceRequestBody Body;
        
        public OutStockbilcanceRequest() {
        }
        
        public OutStockbilcanceRequest(WMS.WMSSV.OutStockbilcanceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Thok.WMS.Interface/")]
    public partial class OutStockbilcanceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string BillNo;
        
        public OutStockbilcanceRequestBody() {
        }
        
        public OutStockbilcanceRequestBody(string BillNo) {
            this.BillNo = BillNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OutStockbilcanceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OutStockbilcanceResponse", Namespace="http://Thok.WMS.Interface/", Order=0)]
        public WMS.WMSSV.OutStockbilcanceResponseBody Body;
        
        public OutStockbilcanceResponse() {
        }
        
        public OutStockbilcanceResponse(WMS.WMSSV.OutStockbilcanceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Thok.WMS.Interface/")]
    public partial class OutStockbilcanceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string OutStockbilcanceResult;
        
        public OutStockbilcanceResponseBody() {
        }
        
        public OutStockbilcanceResponseBody(string OutStockbilcanceResult) {
            this.OutStockbilcanceResult = OutStockbilcanceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OpenCollectionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OpenCollection", Namespace="http://Thok.WMS.Interface/", Order=0)]
        public WMS.WMSSV.OpenCollectionRequestBody Body;
        
        public OpenCollectionRequest() {
        }
        
        public OpenCollectionRequest(WMS.WMSSV.OpenCollectionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Thok.WMS.Interface/")]
    public partial class OpenCollectionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string BillNo;
        
        public OpenCollectionRequestBody() {
        }
        
        public OpenCollectionRequestBody(string BillNo) {
            this.BillNo = BillNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OpenCollectionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OpenCollectionResponse", Namespace="http://Thok.WMS.Interface/", Order=0)]
        public WMS.WMSSV.OpenCollectionResponseBody Body;
        
        public OpenCollectionResponse() {
        }
        
        public OpenCollectionResponse(WMS.WMSSV.OpenCollectionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Thok.WMS.Interface/")]
    public partial class OpenCollectionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string OpenCollectionResult;
        
        public OpenCollectionResponseBody() {
        }
        
        public OpenCollectionResponseBody(string OpenCollectionResult) {
            this.OpenCollectionResult = OpenCollectionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OpenBeginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OpenBegin", Namespace="http://Thok.WMS.Interface/", Order=0)]
        public WMS.WMSSV.OpenBeginRequestBody Body;
        
        public OpenBeginRequest() {
        }
        
        public OpenBeginRequest(WMS.WMSSV.OpenBeginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Thok.WMS.Interface/")]
    public partial class OpenBeginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string BillNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string State;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Startime;
        
        public OpenBeginRequestBody() {
        }
        
        public OpenBeginRequestBody(string BillNo, string State, string Startime) {
            this.BillNo = BillNo;
            this.State = State;
            this.Startime = Startime;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OpenBeginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OpenBeginResponse", Namespace="http://Thok.WMS.Interface/", Order=0)]
        public WMS.WMSSV.OpenBeginResponseBody Body;
        
        public OpenBeginResponse() {
        }
        
        public OpenBeginResponse(WMS.WMSSV.OpenBeginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Thok.WMS.Interface/")]
    public partial class OpenBeginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string OpenBeginResult;
        
        public OpenBeginResponseBody() {
        }
        
        public OpenBeginResponseBody(string OpenBeginResult) {
            this.OpenBeginResult = OpenBeginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OpenEndRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OpenEnd", Namespace="http://Thok.WMS.Interface/", Order=0)]
        public WMS.WMSSV.OpenEndRequestBody Body;
        
        public OpenEndRequest() {
        }
        
        public OpenEndRequest(WMS.WMSSV.OpenEndRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Thok.WMS.Interface/")]
    public partial class OpenEndRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string BillNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string State;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Endtime;
        
        public OpenEndRequestBody() {
        }
        
        public OpenEndRequestBody(string BillNo, string State, string Endtime) {
            this.BillNo = BillNo;
            this.State = State;
            this.Endtime = Endtime;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OpenEndResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OpenEndResponse", Namespace="http://Thok.WMS.Interface/", Order=0)]
        public WMS.WMSSV.OpenEndResponseBody Body;
        
        public OpenEndResponse() {
        }
        
        public OpenEndResponse(WMS.WMSSV.OpenEndResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Thok.WMS.Interface/")]
    public partial class OpenEndResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string OpenEndResult;
        
        public OpenEndResponseBody() {
        }
        
        public OpenEndResponseBody(string OpenEndResult) {
            this.OpenEndResult = OpenEndResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FeedingSendRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FeedingSend", Namespace="http://Thok.WMS.Interface/", Order=0)]
        public WMS.WMSSV.FeedingSendRequestBody Body;
        
        public FeedingSendRequest() {
        }
        
        public FeedingSendRequest(WMS.WMSSV.FeedingSendRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Thok.WMS.Interface/")]
    public partial class FeedingSendRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string BillNo;
        
        public FeedingSendRequestBody() {
        }
        
        public FeedingSendRequestBody(string BillNo) {
            this.BillNo = BillNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FeedingSendResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FeedingSendResponse", Namespace="http://Thok.WMS.Interface/", Order=0)]
        public WMS.WMSSV.FeedingSendResponseBody Body;
        
        public FeedingSendResponse() {
        }
        
        public FeedingSendResponse(WMS.WMSSV.FeedingSendResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Thok.WMS.Interface/")]
    public partial class FeedingSendResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string FeedingSendResult;
        
        public FeedingSendResponseBody() {
        }
        
        public FeedingSendResponseBody(string FeedingSendResult) {
            this.FeedingSendResult = FeedingSendResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AHZY_ESB_WMS_GETSSVSoapChannel : WMS.WMSSV.AHZY_ESB_WMS_GETSSVSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AHZY_ESB_WMS_GETSSVSoapClient : System.ServiceModel.ClientBase<WMS.WMSSV.AHZY_ESB_WMS_GETSSVSoap>, WMS.WMSSV.AHZY_ESB_WMS_GETSSVSoap {
        
        public AHZY_ESB_WMS_GETSSVSoapClient() {
        }
        
        public AHZY_ESB_WMS_GETSSVSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AHZY_ESB_WMS_GETSSVSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AHZY_ESB_WMS_GETSSVSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AHZY_ESB_WMS_GETSSVSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WMS.WMSSV.HelloWorldResponse WMS.WMSSV.AHZY_ESB_WMS_GETSSVSoap.HelloWorld(WMS.WMSSV.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld(string BillNo, string billtype, string finishdate) {
            WMS.WMSSV.HelloWorldRequest inValue = new WMS.WMSSV.HelloWorldRequest();
            inValue.Body = new WMS.WMSSV.HelloWorldRequestBody();
            inValue.Body.BillNo = BillNo;
            inValue.Body.billtype = billtype;
            inValue.Body.finishdate = finishdate;
            WMS.WMSSV.HelloWorldResponse retVal = ((WMS.WMSSV.AHZY_ESB_WMS_GETSSVSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WMS.WMSSV.StockinFinishResponse WMS.WMSSV.AHZY_ESB_WMS_GETSSVSoap.StockinFinish(WMS.WMSSV.StockinFinishRequest request) {
            return base.Channel.StockinFinish(request);
        }
        
        public string StockinFinish(string BillNo, string billtype, string finishdate) {
            WMS.WMSSV.StockinFinishRequest inValue = new WMS.WMSSV.StockinFinishRequest();
            inValue.Body = new WMS.WMSSV.StockinFinishRequestBody();
            inValue.Body.BillNo = BillNo;
            inValue.Body.billtype = billtype;
            inValue.Body.finishdate = finishdate;
            WMS.WMSSV.StockinFinishResponse retVal = ((WMS.WMSSV.AHZY_ESB_WMS_GETSSVSoap)(this)).StockinFinish(inValue);
            return retVal.Body.StockinFinishResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WMS.WMSSV.StockbackFinishResponse WMS.WMSSV.AHZY_ESB_WMS_GETSSVSoap.StockbackFinish(WMS.WMSSV.StockbackFinishRequest request) {
            return base.Channel.StockbackFinish(request);
        }
        
        public string StockbackFinish(string BillNo, string billtype, string finishdate) {
            WMS.WMSSV.StockbackFinishRequest inValue = new WMS.WMSSV.StockbackFinishRequest();
            inValue.Body = new WMS.WMSSV.StockbackFinishRequestBody();
            inValue.Body.BillNo = BillNo;
            inValue.Body.billtype = billtype;
            inValue.Body.finishdate = finishdate;
            WMS.WMSSV.StockbackFinishResponse retVal = ((WMS.WMSSV.AHZY_ESB_WMS_GETSSVSoap)(this)).StockbackFinish(inValue);
            return retVal.Body.StockbackFinishResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WMS.WMSSV.FeedFinishResponse WMS.WMSSV.AHZY_ESB_WMS_GETSSVSoap.FeedFinish(WMS.WMSSV.FeedFinishRequest request) {
            return base.Channel.FeedFinish(request);
        }
        
        public string FeedFinish(string BillNo, string billtype, string finishdate) {
            WMS.WMSSV.FeedFinishRequest inValue = new WMS.WMSSV.FeedFinishRequest();
            inValue.Body = new WMS.WMSSV.FeedFinishRequestBody();
            inValue.Body.BillNo = BillNo;
            inValue.Body.billtype = billtype;
            inValue.Body.finishdate = finishdate;
            WMS.WMSSV.FeedFinishResponse retVal = ((WMS.WMSSV.AHZY_ESB_WMS_GETSSVSoap)(this)).FeedFinish(inValue);
            return retVal.Body.FeedFinishResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WMS.WMSSV.StockOutBeginResponse WMS.WMSSV.AHZY_ESB_WMS_GETSSVSoap.StockOutBegin(WMS.WMSSV.StockOutBeginRequest request) {
            return base.Channel.StockOutBegin(request);
        }
        
        public string StockOutBegin(string BillNo, string State, string Startime) {
            WMS.WMSSV.StockOutBeginRequest inValue = new WMS.WMSSV.StockOutBeginRequest();
            inValue.Body = new WMS.WMSSV.StockOutBeginRequestBody();
            inValue.Body.BillNo = BillNo;
            inValue.Body.State = State;
            inValue.Body.Startime = Startime;
            WMS.WMSSV.StockOutBeginResponse retVal = ((WMS.WMSSV.AHZY_ESB_WMS_GETSSVSoap)(this)).StockOutBegin(inValue);
            return retVal.Body.StockOutBeginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WMS.WMSSV.StockOutEndResponse WMS.WMSSV.AHZY_ESB_WMS_GETSSVSoap.StockOutEnd(WMS.WMSSV.StockOutEndRequest request) {
            return base.Channel.StockOutEnd(request);
        }
        
        public string StockOutEnd(string BillNo, string State, string Endtime) {
            WMS.WMSSV.StockOutEndRequest inValue = new WMS.WMSSV.StockOutEndRequest();
            inValue.Body = new WMS.WMSSV.StockOutEndRequestBody();
            inValue.Body.BillNo = BillNo;
            inValue.Body.State = State;
            inValue.Body.Endtime = Endtime;
            WMS.WMSSV.StockOutEndResponse retVal = ((WMS.WMSSV.AHZY_ESB_WMS_GETSSVSoap)(this)).StockOutEnd(inValue);
            return retVal.Body.StockOutEndResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WMS.WMSSV.StockOutCollectionResponse WMS.WMSSV.AHZY_ESB_WMS_GETSSVSoap.StockOutCollection(WMS.WMSSV.StockOutCollectionRequest request) {
            return base.Channel.StockOutCollection(request);
        }
        
        public string StockOutCollection(string BillNo) {
            WMS.WMSSV.StockOutCollectionRequest inValue = new WMS.WMSSV.StockOutCollectionRequest();
            inValue.Body = new WMS.WMSSV.StockOutCollectionRequestBody();
            inValue.Body.BillNo = BillNo;
            WMS.WMSSV.StockOutCollectionResponse retVal = ((WMS.WMSSV.AHZY_ESB_WMS_GETSSVSoap)(this)).StockOutCollection(inValue);
            return retVal.Body.StockOutCollectionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WMS.WMSSV.FeedingReplaceResponse WMS.WMSSV.AHZY_ESB_WMS_GETSSVSoap.FeedingReplace(WMS.WMSSV.FeedingReplaceRequest request) {
            return base.Channel.FeedingReplace(request);
        }
        
        public string FeedingReplace(string BillNo, string Transer) {
            WMS.WMSSV.FeedingReplaceRequest inValue = new WMS.WMSSV.FeedingReplaceRequest();
            inValue.Body = new WMS.WMSSV.FeedingReplaceRequestBody();
            inValue.Body.BillNo = BillNo;
            inValue.Body.Transer = Transer;
            WMS.WMSSV.FeedingReplaceResponse retVal = ((WMS.WMSSV.AHZY_ESB_WMS_GETSSVSoap)(this)).FeedingReplace(inValue);
            return retVal.Body.FeedingReplaceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WMS.WMSSV.OutStockbillreplaceResponse WMS.WMSSV.AHZY_ESB_WMS_GETSSVSoap.OutStockbillreplace(WMS.WMSSV.OutStockbillreplaceRequest request) {
            return base.Channel.OutStockbillreplace(request);
        }
        
        public string OutStockbillreplace(string channel_no) {
            WMS.WMSSV.OutStockbillreplaceRequest inValue = new WMS.WMSSV.OutStockbillreplaceRequest();
            inValue.Body = new WMS.WMSSV.OutStockbillreplaceRequestBody();
            inValue.Body.channel_no = channel_no;
            WMS.WMSSV.OutStockbillreplaceResponse retVal = ((WMS.WMSSV.AHZY_ESB_WMS_GETSSVSoap)(this)).OutStockbillreplace(inValue);
            return retVal.Body.OutStockbillreplaceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WMS.WMSSV.OutStockbilcanceResponse WMS.WMSSV.AHZY_ESB_WMS_GETSSVSoap.OutStockbilcance(WMS.WMSSV.OutStockbilcanceRequest request) {
            return base.Channel.OutStockbilcance(request);
        }
        
        public string OutStockbilcance(string BillNo) {
            WMS.WMSSV.OutStockbilcanceRequest inValue = new WMS.WMSSV.OutStockbilcanceRequest();
            inValue.Body = new WMS.WMSSV.OutStockbilcanceRequestBody();
            inValue.Body.BillNo = BillNo;
            WMS.WMSSV.OutStockbilcanceResponse retVal = ((WMS.WMSSV.AHZY_ESB_WMS_GETSSVSoap)(this)).OutStockbilcance(inValue);
            return retVal.Body.OutStockbilcanceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WMS.WMSSV.OpenCollectionResponse WMS.WMSSV.AHZY_ESB_WMS_GETSSVSoap.OpenCollection(WMS.WMSSV.OpenCollectionRequest request) {
            return base.Channel.OpenCollection(request);
        }
        
        public string OpenCollection(string BillNo) {
            WMS.WMSSV.OpenCollectionRequest inValue = new WMS.WMSSV.OpenCollectionRequest();
            inValue.Body = new WMS.WMSSV.OpenCollectionRequestBody();
            inValue.Body.BillNo = BillNo;
            WMS.WMSSV.OpenCollectionResponse retVal = ((WMS.WMSSV.AHZY_ESB_WMS_GETSSVSoap)(this)).OpenCollection(inValue);
            return retVal.Body.OpenCollectionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WMS.WMSSV.OpenBeginResponse WMS.WMSSV.AHZY_ESB_WMS_GETSSVSoap.OpenBegin(WMS.WMSSV.OpenBeginRequest request) {
            return base.Channel.OpenBegin(request);
        }
        
        public string OpenBegin(string BillNo, string State, string Startime) {
            WMS.WMSSV.OpenBeginRequest inValue = new WMS.WMSSV.OpenBeginRequest();
            inValue.Body = new WMS.WMSSV.OpenBeginRequestBody();
            inValue.Body.BillNo = BillNo;
            inValue.Body.State = State;
            inValue.Body.Startime = Startime;
            WMS.WMSSV.OpenBeginResponse retVal = ((WMS.WMSSV.AHZY_ESB_WMS_GETSSVSoap)(this)).OpenBegin(inValue);
            return retVal.Body.OpenBeginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WMS.WMSSV.OpenEndResponse WMS.WMSSV.AHZY_ESB_WMS_GETSSVSoap.OpenEnd(WMS.WMSSV.OpenEndRequest request) {
            return base.Channel.OpenEnd(request);
        }
        
        public string OpenEnd(string BillNo, string State, string Endtime) {
            WMS.WMSSV.OpenEndRequest inValue = new WMS.WMSSV.OpenEndRequest();
            inValue.Body = new WMS.WMSSV.OpenEndRequestBody();
            inValue.Body.BillNo = BillNo;
            inValue.Body.State = State;
            inValue.Body.Endtime = Endtime;
            WMS.WMSSV.OpenEndResponse retVal = ((WMS.WMSSV.AHZY_ESB_WMS_GETSSVSoap)(this)).OpenEnd(inValue);
            return retVal.Body.OpenEndResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WMS.WMSSV.FeedingSendResponse WMS.WMSSV.AHZY_ESB_WMS_GETSSVSoap.FeedingSend(WMS.WMSSV.FeedingSendRequest request) {
            return base.Channel.FeedingSend(request);
        }
        
        public string FeedingSend(string BillNo) {
            WMS.WMSSV.FeedingSendRequest inValue = new WMS.WMSSV.FeedingSendRequest();
            inValue.Body = new WMS.WMSSV.FeedingSendRequestBody();
            inValue.Body.BillNo = BillNo;
            WMS.WMSSV.FeedingSendResponse retVal = ((WMS.WMSSV.AHZY_ESB_WMS_GETSSVSoap)(this)).FeedingSend(inValue);
            return retVal.Body.FeedingSendResult;
        }
    }
}
